export const STORAGE_KEYS = [
  '@vitalspan_articles_last_fetched',
  '@vitalspan_biomarkers',
  '@vitalspan_disclaimer_accepted',
  '@vitalspan_dismissed_insights',
  '@vitalspan_email_verified_notified',
  '@vitalspan_exercise_log',
  '@vitalspan_exercise_routine',
  '@vitalspan_first_run_complete',
  '@vitalspan_health_data',
  '@vitalspan_health_permissions',
  '@vitalspan_identity_linked',
  '@vitalspan_last_report_ts',
  '@vitalspan_migrated_v2',
  '@vitalspan_notification_prefs',
  '@vitalspan_protocol',
  '@vitalspan_protocol_today',
  '@vitalspan_rxnav_cache',
  '@vitalspan_user_profile',
] as const;
