import type { KdmHistoricalBiomarkerSpecification } from './contracts';

const publication = ['levine_2013_primary'] as const;
const laboratory = ['levine_2013_primary', 'nhanes_iii_laboratory_codebook', 'nhanes_iii_laboratory_manual'] as const;

export const KDM_HISTORICAL_BIOMARKERS = [
  {
    id: 'crp',
    officialName: 'Serum C-reactive protein',
    publicationLabel: 'C-reactive protein (mg/dL)',
    nhanesVariableCandidates: ['CRP'],
    mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'mg/dL', evidenceIds: laboratory, rationale: 'The paper and archive use the same label and unit.' },
    historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 0.21, maximum: 25.2, qualifier: 'observed_archive_encoding', note: '0.21 encodes below detection; measured values begin at 0.3 mg/dL.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'This is an archive encoding range, not a scientific eligibility range.' },
    productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'The primary publication does not define runtime bounds.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum', evidenceIds: laboratory, rationale: 'The archive and procedure manual identify serum.' },
    historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Latex-enhanced nephelometric immunoassay using rabbit anti-human CRP-coated particles.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Documented in the NHANES III procedure manual.' },
    historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Behring Nephelometric Analyzer.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Documented in the NHANES III procedure manual.' },
    modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'A traceable serum CRP assay may be analytically bridged; hs-CRP is not automatically interchangeable.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Method comparison is required before accepting a modern assay.' },
    knownDrift: ['Historical reporting was coarse below 0.3 mg/dL.', 'Lipemia, icterus, hemolysis, and rabbit-protein reactions can affect the historical assay.'],
    internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No log or other model-input transformation is reported.' },
    qualityControl: ['Reject silent substitution of hs-CRP.', 'Preserve below-detection semantics.', 'Record acute infection and inflammatory collection context.'],
    acuteIllnessSensitivity: 'high', clinicalPhenoAgeOverlap: 'exact', overlapNote: 'Exact analyte overlap creates correlated-information risk.', controversies: ['The primary paper does not say how below-detection CRP was represented.'], evidenceIds: laboratory,
  },
  {
    id: 'creatinine', officialName: 'Serum creatinine', publicationLabel: 'Serum creatinine (mg/dL)', nhanesVariableCandidates: ['CEP'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'mg/dL', evidenceIds: laboratory, rationale: 'The paper and archive agree.' },
    historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 0.3, maximum: 13.9, qualifier: 'observed_archive_encoding', note: 'Public-file observed range.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'Not a production eligibility range.' },
    productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum', evidenceIds: laboratory, rationale: 'Official NHANES definition.' },
    historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Kinetic Jaffe alkaline-picrate reaction.', evidenceIds: laboratory, rationale: 'Official method documentation.' },
    historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Roche/Hitachi 737 multichannel analyzer.', evidenceIds: laboratory, rationale: 'Official method documentation.' },
    modernEquivalent: { resolution: 'conflicted', confidence: 'high', value: 'Modern IDMS-traceable creatinine differs systematically from the archived result; the paper does not disclose whether the later NHANES correction was applied.', evidenceIds: laboratory, rationale: 'CDC documents material drift and recommends correction, but Levine does not state the chosen representation.' },
    knownDrift: ['CDC found significant difference between archived Jaffe results and later IDMS-traceable enzymatic measurements.', 'Applying or omitting the archive correction changes calibration identity.'],
    internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'Correction and model-input transformation are undisclosed.' },
    qualityControl: ['Require assay traceability.', 'Do not apply the NHANES correction without resolving the historical choice.', 'Record specimen and calibration method.'],
    acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'exact', overlapNote: 'Exact analyte overlap with Clinical PhenoAge.', controversies: ['Historical corrected-versus-uncorrected input is unresolved.'], evidenceIds: laboratory,
  },
  {
    id: 'hba1c', officialName: 'Glycated hemoglobin (HbA1c)', publicationLabel: 'Glycated hemoglobin (%)', nhanesVariableCandidates: ['GHP', 'GHPMETH'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: '%', evidenceIds: laboratory, rationale: 'Paper and archive agree.' },
    historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 2.8, maximum: 16.2, qualifier: 'observed_archive_encoding', note: 'Public-file observed range.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'Not a production eligibility range.' },
    productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'EDTA whole blood', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' },
    historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Bio-Rad Diamat ion-exchange HPLC; DCCT-standardized affinity chromatography for specified abnormal chromatograms or variants.', evidenceIds: laboratory, rationale: 'NHANES retains a method flag.' },
    historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Bio-Rad Diamat model 723 instruments; alternate standardized affinity method.', evidenceIds: laboratory, rationale: 'Official procedure manual and codebook.' },
    modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'NGSP/DCCT-traceable HbA1c with documented variant handling may be bridgeable, but is not automatically equivalent.', evidenceIds: laboratory, rationale: 'Historical method branching and chromatogram review matter.' },
    knownDrift: ['Three Diamat instrument codes and one affinity-method code exist.', 'Hemoglobin variants and degradation prompted method substitution.'],
    internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' },
    qualityControl: ['Require method and variant-interference metadata.', 'Reject unknown method quality.', 'Do not conflate IFCC mmol/mol with percent without validated explicit conversion outside the scientific engine.'],
    acuteIllnessSensitivity: 'low', clinicalPhenoAgeOverlap: 'related', overlapNote: 'Related glycemic information; Clinical PhenoAge uses glucose, not HbA1c.', controversies: ['The paper does not state whether GHPMETH affected inclusion or calibration.'], evidenceIds: laboratory,
  },
  {
    id: 'systolic_blood_pressure', officialName: 'Systolic blood pressure', publicationLabel: 'Systolic blood pressure', nhanesVariableCandidates: ['PEPMNK1R'], mappingStatus: 'ambiguous',
    requiredUnit: { resolution: 'partially_resolved', confidence: 'high', value: 'mmHg', evidenceIds: ['nhanes_iii_examination_codebook', 'nhanes_iii_blood_pressure_manual'], rationale: 'NHANES definition is clear; the paper omits the unit and variable.' },
    historicalRange: { resolution: 'partially_resolved', confidence: 'moderate', value: { minimum: 53, maximum: 244, qualifier: 'observed_archive_encoding', note: 'Range of PEPMNK1R, the strongest public candidate.' }, evidenceIds: ['nhanes_iii_examination_codebook'], rationale: 'Variable mapping is not confirmed by the publication.' },
    productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'Seated auscultatory blood-pressure examination', evidenceIds: ['nhanes_iii_blood_pressure_manual'], rationale: 'Official procedure context.' },
    historicalMethod: { resolution: 'partially_resolved', confidence: 'moderate', value: 'Candidate PEPMNK1R is the arithmetic mean of up to six K1 readings from household and MEC measurements.', evidenceIds: ['nhanes_iii_examination_codebook'], rationale: 'This is the best matching archive variable, but the paper never names it.' },
    historicalInstrumentation: { resolution: 'partially_resolved', confidence: 'moderate', value: 'NHANES III standardized auscultatory protocol; exact device linkage for the analytic value is not stated in the paper.', evidenceIds: ['nhanes_iii_blood_pressure_manual'], rationale: 'Archive procedure is known; study selection is not.' },
    modernEquivalent: { resolution: 'unknown', confidence: 'limited', value: null, evidenceIds: publication, rationale: 'A single oscillometric reading cannot be presumed equivalent to the historical multi-reading average.' },
    knownDrift: ['Device type, cuff, rest, observer, and number of readings affect comparability.'], internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' },
    qualityControl: ['Require repeated validated measurements.', 'Retain protocol, device, cuff, posture, and reading count.', 'Do not substitute a self-reported diagnosis or treatment status.'],
    acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'none', overlapNote: 'No direct Clinical PhenoAge analyte overlap.', controversies: ['Exact NHANES systolic variable is not disclosed.'], evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook', 'nhanes_iii_blood_pressure_manual'],
  },
  {
    id: 'albumin', officialName: 'Serum albumin', publicationLabel: 'Serum albumin (g/dL)', nhanesVariableCandidates: ['AMP'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'g/dL', evidenceIds: laboratory, rationale: 'Paper and archive agree.' }, historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 0.9, maximum: 6.1, qualifier: 'observed_archive_encoding', note: 'Public-file observed range.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'Not a production eligibility range.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum', evidenceIds: laboratory, rationale: 'Official NHANES definition.' }, historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Bromcresol purple dye-binding method with sample blank.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Hitachi 737 multichannel analyzer.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'Modern serum albumin by bromcresol purple may be bridgeable; bromcresol green is not a silent substitute.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Dye methods can differ.' },
    knownDrift: ['BCP and BCG albumin methods are not interchangeable without comparison.'], internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' }, qualityControl: ['Require serum and assay-method identity.', 'Record hydration and acute inflammatory context.'], acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'exact', overlapNote: 'Exact analyte overlap with Clinical PhenoAge.', controversies: ['The study does not document analytic range handling.'], evidenceIds: laboratory,
  },
  {
    id: 'total_cholesterol', officialName: 'Serum total cholesterol', publicationLabel: 'Serum total cholesterol (mg/dL)', nhanesVariableCandidates: ['TCP', 'CHP'], mappingStatus: 'ambiguous',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'mg/dL', evidenceIds: laboratory, rationale: 'Paper and both archive candidates agree on unit.' }, historicalRange: { resolution: 'partially_resolved', confidence: 'moderate', value: { minimum: 59, maximum: 702, qualifier: 'observed_archive_encoding', note: 'Range for TCP, the CDC-recommended formal lipid variable.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'The paper does not distinguish TCP from CHP.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' },
    specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum or plasma', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Formal lipid procedure.' }, historicalMethod: { resolution: 'partially_resolved', confidence: 'moderate', value: 'TCP used an enzymatic coupled-reaction lipid method standardized by the CDC lipid program; CHP was a separate Hitachi biochemistry value that CDC advises against for routine analysis.', evidenceIds: laboratory, rationale: 'TCP is scientifically preferable, but study use is not explicitly identified.' }, historicalInstrumentation: { resolution: 'partially_resolved', confidence: 'moderate', value: 'TCP: Hitachi 704 lipid analyzer; CHP: Hitachi 737 biochemistry analyzer.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Two public variables exist.' }, modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'CDC-traceable enzymatic total cholesterol may be bridgeable after method verification.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Exact historical variable must first be established.' },
    knownDrift: ['TCP and CHP are distinct public measurements.', 'CDC explicitly recommends TCP for most analyses.'], internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' }, qualityControl: ['Resolve TCP versus CHP before implementation.', 'Require traceable total cholesterol; do not derive from lipid fractions.'], acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'none', overlapNote: 'No direct Clinical PhenoAge analyte overlap.', controversies: ['Exact NHANES cholesterol variable is undisclosed.'], evidenceIds: laboratory,
  },
  {
    id: 'cmv_optical_density', officialName: 'Cytomegalovirus IgG optical density', publicationLabel: 'Cytomegalovirus optical density', nhanesVariableCandidates: ['CMPODgT', 'CMPODgV', 'CVP_IGG'], mappingStatus: 'incompatible_public_artifact',
    requiredUnit: { resolution: 'conflicted', confidence: 'high', value: null, evidenceIds: ['levine_2013_primary', 'nhanes_iii_cmv_status', 'nhanes_iii_cmv_optical_density'], rationale: 'The paper reports no unit; continuous public variables use incompatible arbitrary/absorbance units, while the mixed-sex file is categorical.' }, historicalRange: { resolution: 'conflicted', confidence: 'high', value: null, evidenceIds: ['nhanes_iii_cmv_optical_density'], rationale: 'CMPODgT and CMPODgV have different ranges and neither covers the reported mixed-sex age 30–75 cohort.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range or assay identity was published.' },
    specimen: { resolution: 'partially_resolved', confidence: 'high', value: 'Stored serum', evidenceIds: ['nhanes_iii_cmv_status', 'nhanes_iii_cmv_optical_density'], rationale: 'Official surplus-sera documentation.' }, historicalMethod: { resolution: 'conflicted', confidence: 'high', value: null, evidenceIds: ['nhanes_iii_cmv_status', 'nhanes_iii_cmv_optical_density'], rationale: 'Quest Triturus ELISA provides continuous OD for women 12–49; VIDAS confirms a subset; the age-six-plus mixed-sex file releases categorical IgG only.' }, historicalInstrumentation: { resolution: 'conflicted', confidence: 'high', value: null, evidenceIds: ['nhanes_iii_cmv_optical_density'], rationale: 'Triturus and VIDAS outputs are different and study use cannot be identified.' }, modernEquivalent: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: ['nhanes_iii_cmv_optical_density'], rationale: 'Generic modern CMV serology cannot reproduce an unidentified continuous assay scale.' },
    knownDrift: ['Optical density is assay-, reagent-, platform-, and dilution-dependent.', 'Categorical serostatus is not a substitute for continuous optical density.', 'CMPODgT values above its detectable range carry a special archive code.'], internationalAvailability: 'specialty', clinicalRoutineAvailability: 'not_routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'Assay identity and input handling are undisclosed.' }, qualityControl: ['Block all execution until the original continuous artifact and scale are authenticated.', 'Never map categorical CVP_IGG to a numeric optical-density value.', 'Never substitute a different commercial CMV assay.'], acuteIllnessSensitivity: 'variable', clinicalPhenoAgeOverlap: 'none', overlapNote: 'No Clinical PhenoAge overlap.', controversies: ['Public continuous data are women-only and age-limited.', 'The paper reports CMV optical density for male and female calibrations through age 75.', 'Faithful modern reproduction may be impossible without the original artifact and a bridging study.'], evidenceIds: ['levine_2013_primary', 'nhanes_iii_cmv_status', 'nhanes_iii_cmv_optical_density'],
  },
  {
    id: 'alkaline_phosphatase', officialName: 'Serum alkaline phosphatase', publicationLabel: 'Serum alkaline phosphatase SI (U/L)', nhanesVariableCandidates: ['APPSI'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'U/L', evidenceIds: laboratory, rationale: 'Paper and archive agree.' }, historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 17, maximum: 952, qualifier: 'observed_archive_encoding', note: 'Public-file observed range.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'Not a production eligibility range.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' }, specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum', evidenceIds: laboratory, rationale: 'Official NHANES definition.' }, historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Kinetic p-nitrophenylphosphate hydrolysis in the presence of magnesium.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Hitachi 737 multichannel analyzer.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'A temperature- and method-traceable total ALP activity assay may be bridgeable.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Enzyme activity depends on method and temperature.' }, knownDrift: ['Modern IFCC procedures and reporting temperatures may not reproduce the historical activity scale.'], internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' }, qualityControl: ['Require total ALP activity, method, temperature, and unit provenance.', 'Do not substitute an isoenzyme result.'], acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'exact', overlapNote: 'Exact analyte overlap with Clinical PhenoAge.', controversies: ['Assay equivalence across modern platforms is unvalidated for this calibration.'], evidenceIds: laboratory,
  },
  {
    id: 'fev1', officialName: 'Forced expiratory volume in one second', publicationLabel: 'Forced expiratory volume (mL)', nhanesVariableCandidates: ['SPPFEV1', 'SPPTYPE', 'SPPREPRO', 'SPPRELIA', 'SPPMANEU'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'mL', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook'], rationale: 'Paper and archive agree.' }, historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 104, maximum: 6572, qualifier: 'observed_archive_encoding', note: 'Public-file observed range for SPPFEV1.' }, evidenceIds: ['nhanes_iii_examination_codebook'], rationale: 'Not a production eligibility range.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' }, specimen: { resolution: 'resolved', confidence: 'high', value: 'Forced expiratory maneuver', evidenceIds: ['nhanes_iii_examination_codebook', 'nhanes_iii_spirometry_manual'], rationale: 'Largest volume from acceptable maneuvers.' }, historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Largest FEV1 from acceptable FVC maneuvers under NHANES/ATS quality procedures.', evidenceIds: ['nhanes_iii_examination_codebook', 'nhanes_iii_spirometry_manual'], rationale: 'Official definition.' }, historicalInstrumentation: { resolution: 'partially_resolved', confidence: 'high', value: 'MEC customized Ohio 822/827 dry rolling-seal spirometers; three home flow-spirometer types also existed.', evidenceIds: ['nhanes_iii_examination_codebook'], rationale: 'The paper does not disclose device-type inclusion.' }, modernEquivalent: { resolution: 'partially_resolved', confidence: 'limited', value: 'ATS/ERS-quality modern spirometry may be clinically comparable, but device and calibration equivalence to the historical mixed instrument set is unproven.', evidenceIds: ['nhanes_iii_examination_codebook', 'nhanes_iii_spirometry_manual'], rationale: 'A bridging specification is required.' }, knownDrift: ['Flow and volume spirometers differ.', 'Home devices did not all provide equivalent quality assessment.', 'Modern reference corrections and BTPS handling must be explicitly matched.'], internationalAvailability: 'variable', clinicalRoutineAvailability: 'specialty', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No height normalization, percent-predicted conversion, or other transformation is reported; the paper labels raw mL.' }, qualityControl: ['Require acceptable maneuver count and reliable review state.', 'Record device, calibration, temperature, protocol, and acute respiratory screening.', 'Do not use consumer estimated lung function.'], acuteIllnessSensitivity: 'high', clinicalPhenoAgeOverlap: 'none', overlapNote: 'No Clinical PhenoAge overlap.', controversies: ['Paper does not state whether unreliable, nonreproducible, acute-illness, or home tests were excluded.'], evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook', 'nhanes_iii_spirometry_manual'],
  },
  {
    id: 'bun', officialName: 'Serum blood urea nitrogen', publicationLabel: 'Serum urea nitrogen (mg/dL)', nhanesVariableCandidates: ['BUP'], mappingStatus: 'strong_candidate',
    requiredUnit: { resolution: 'resolved', confidence: 'very_high', value: 'mg/dL', evidenceIds: laboratory, rationale: 'Paper and archive agree.' }, historicalRange: { resolution: 'resolved', confidence: 'high', value: { minimum: 2, maximum: 104, qualifier: 'observed_archive_encoding', note: 'Public-file observed range.' }, evidenceIds: ['nhanes_iii_laboratory_codebook'], rationale: 'Not a production eligibility range.' }, productionAllowedRange: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No runtime range was published.' }, specimen: { resolution: 'resolved', confidence: 'high', value: 'Serum', evidenceIds: laboratory, rationale: 'Official NHANES definition.' }, historicalMethod: { resolution: 'resolved', confidence: 'high', value: 'Kinetic urease/glutamate-dehydrogenase method measuring NADH consumption.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, historicalInstrumentation: { resolution: 'resolved', confidence: 'high', value: 'Hitachi 737 multichannel analyzer.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Official procedure manual.' }, modernEquivalent: { resolution: 'partially_resolved', confidence: 'moderate', value: 'Traceable enzymatic serum BUN using equivalent reporting units may be bridgeable.', evidenceIds: ['nhanes_iii_laboratory_manual'], rationale: 'Method comparison remains required.' }, knownDrift: ['Hydration, diet, catabolism, and renal context affect within-person values.'], internationalAvailability: 'routine', clinicalRoutineAvailability: 'routine', transformationBeforeModel: { resolution: 'unknown', confidence: 'insufficient', value: null, evidenceIds: publication, rationale: 'No transformation is reported.' }, qualityControl: ['Distinguish BUN from urea concentration.', 'Require explicit unit and specimen identity.', 'Record collection context.'], acuteIllnessSensitivity: 'moderate', clinicalPhenoAgeOverlap: 'none', overlapNote: 'No direct Clinical PhenoAge analyte overlap.', controversies: ['International laboratories often report urea rather than BUN.'], evidenceIds: laboratory,
  },
] as const satisfies readonly KdmHistoricalBiomarkerSpecification[];

export function getKdmHistoricalBiomarker(id: string): KdmHistoricalBiomarkerSpecification | undefined {
  return KDM_HISTORICAL_BIOMARKERS.find(biomarker => biomarker.id === id);
}
