import type { KdmHistoricalOpenQuestion } from './contracts';

export const KDM_HISTORICAL_OPEN_QUESTIONS = [
  { id: 'cmv_source_artifact', question: 'Which continuous CMV optical-density artifact was used for both sexes ages 30–75?', route: 'cannot_currently_be_resolved', severity: 'blocking', currentFinding: 'No compatible public artifact was identified.', requiredResolutionArtifact: 'Author-held code/data dictionary or authenticated archive artifact with participant coverage and assay scale.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_cmv_status', 'nhanes_iii_cmv_optical_density'] },
  { id: 'cmv_assay_variable', question: 'Was the intended CMV value Triturus OD, VIDAS arbitrary units, another continuous value, or a derived measure?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'The public continuous variables are assay-specific and population-incompatible.', requiredResolutionArtifact: 'Official variable lineage or original analytic code.', evidenceIds: ['nhanes_iii_cmv_optical_density'] },
  { id: 'original_parameters', question: 'Where are the complete male and female KDM1 parameter artifacts?', route: 'cannot_currently_be_resolved', severity: 'blocking', currentFinding: 'The publication prints only partial summaries.', requiredResolutionArtifact: 'Authenticated author or journal artifact with immutable provenance.', evidenceIds: ['levine_2013_primary'] },
  { id: 'exact_age_variable', question: 'Did calibration use HSAGEIR or an examination-age derivation?', route: 'requires_nhanes_investigation', severity: 'material', currentFinding: 'HSAGEIR is the official general-analysis recommendation, but the paper does not name it.', requiredResolutionArtifact: 'Original analytic code or an exact sample reproduction.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook'] },
  { id: 'exact_sbp_variable', question: 'Did calibration use PEPMNK1R or another systolic blood-pressure construction?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'PEPMNK1R is the strongest label match but remains unverified.', requiredResolutionArtifact: 'Original variable list or exact sample/summary reproduction.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook'] },
  { id: 'exact_cholesterol_variable', question: 'Did calibration use TCP or CHP?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'CDC recommends TCP; the paper says only serum total cholesterol.', requiredResolutionArtifact: 'Original variable list or exact summary reproduction.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_laboratory_codebook'] },
  { id: 'creatinine_correction', question: 'Was archived CEP corrected to the later standardized creatinine representation?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'CDC recommends a correction; the 2013 paper is silent.', requiredResolutionArtifact: 'Original preprocessing code or author confirmation.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_laboratory_codebook'] },
  { id: 'transformations', question: 'Were any biomarkers logged, centered, scaled, normalized, or winsorized?', route: 'cannot_currently_be_resolved', severity: 'blocking', currentFinding: 'The primary publication does not document these operations.', requiredResolutionArtifact: 'Original analytic code or a methodological supplement.', evidenceIds: ['levine_2013_primary', 'kwon_belsky_bioage_2021'] },
  { id: 'below_detection', question: 'How was below-detection CRP represented?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'The archive encoding is known; use in calibration is not.', requiredResolutionArtifact: 'Original preprocessing code.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_laboratory_codebook'] },
  { id: 'spirometry_quality', question: 'Which device types and reliability/reproducibility flags were eligible?', route: 'requires_nhanes_investigation', severity: 'blocking', currentFinding: 'NHANES exposes quality metadata; the paper reports only complete biomarkers.', requiredResolutionArtifact: 'Original exclusion logic and device-type policy.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook', 'nhanes_iii_spirometry_manual'] },
  { id: 'acute_illness', question: 'Were acute illness, respiratory infection, chemotherapy, pregnancy, or other collection contexts excluded?', route: 'requires_nhanes_investigation', severity: 'material', currentFinding: 'NHANES collected relevant context, but study exclusions are not reported.', requiredResolutionArtifact: 'Original inclusion/exclusion program.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook', 'nhanes_iii_laboratory_codebook'] },
  { id: 'survey_design', question: 'Were NHANES weights, strata, clusters, or subsample weights used during calibration?', route: 'requires_statistical_reconstruction', severity: 'blocking', currentFinding: 'The primary methods do not state survey-design handling.', requiredResolutionArtifact: 'Original statistical program or a uniquely matching independent reconstruction.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook'] },
  { id: 'sample_reproduction', question: 'Can all published sample counts and biomarker summaries be independently reproduced from an authenticated release snapshot?', route: 'requires_statistical_reconstruction', severity: 'blocking', currentFinding: 'The CMV conflict prevents a public-data-only reproduction.', requiredResolutionArtifact: 'Independent locked reconstruction with traceable source hashes.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_data_files', 'nhanes_iii_cmv_optical_density'] },
  { id: 'modern_assay_bridge', question: 'Can current assays and spirometers be bridged to the historical measurement definitions without recalibration?', route: 'requires_expert_review', severity: 'blocking', currentFinding: 'Analytic drift is documented or plausible for multiple inputs.', requiredResolutionArtifact: 'Laboratory-medicine, pulmonology, and biostatistical bridging study.', evidenceIds: ['nhanes_iii_laboratory_manual', 'nhanes_iii_spirometry_manual'] },
  { id: 'sex_branch_policy', question: 'What scientifically valid behaviour applies when a user cannot be mapped to a historically supported sex branch?', route: 'requires_expert_review', severity: 'blocking', currentFinding: 'The historical model offers only male and female branches.', requiredResolutionArtifact: 'Ethical, clinical, statistical, and governance policy; until then return unavailable.', evidenceIds: ['levine_2013_primary', 'nhanes_iii_examination_codebook'] },
  { id: 'external_transportability', question: 'Does the exact calibration transport to current international consumer populations?', route: 'requires_expert_review', severity: 'material', currentFinding: 'The original paper cautions against use in dissimilar populations.', requiredResolutionArtifact: 'Prospective external validation using an authenticated implementation.', evidenceIds: ['levine_2013_primary'] },
] as const satisfies readonly KdmHistoricalOpenQuestion[];
