import type {
  DomainContextRoleMapping,
  ScientificModelComponentMapping,
} from './contracts';

/** Conservative role mapping for every entry in the current scientific registry. */
export const SCIENTIFIC_MODEL_COMPONENT_MAPPINGS = [
  {
    scientificModelId: 'clinical_phenoage',
    componentRole: 'primary_age_estimate',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: 'clinical-phenoage/1.0.0',
    currentAvailability: 'production',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'age_model_output_only',
    rationale: [
      'Clinical PhenoAge v1.0.0 is the only validated production age model.',
      'It reports Blood-Based Phenotypic Age, not Multimodal Biological Age.',
      'A single age model cannot authorize a multimodal result.',
    ],
  },
  {
    scientificModelId: 'kdm_biological_age',
    componentRole: 'independent_age_estimate',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: null,
    currentAvailability: 'future_unavailable',
    combinationStatus: 'unknown',
    numericAgeInfluence: 'age_model_output_only',
    rationale: [
      'KDM is a method, not one executable model.',
      'A named calibration, population, biomarker panel, version, and independent validation are required.',
    ],
  },
  {
    scientificModelId: 'levine_2013_kdm',
    componentRole: 'research_only',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: 'levine-kdm-nhanes-iii/1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['Historical NHANES III calibration remains research-only and is not a production component.'],
  },
  {
    scientificModelId: 'dnam_phenoage',
    componentRole: 'research_only',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: 'dnam-phenoage/1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['Assay, preprocessing, licensing, and production validation remain unresolved.'],
  },
  {
    scientificModelId: 'dunedinpace',
    componentRole: 'pace_of_aging_measure',
    outputConstruct: 'pace_per_biological_year',
    outputUnit: 'pace_per_biological_year',
    currentModelVersion: 'dunedinpace/1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['DunedinPACE is a pace construct, not age in years, and remains research-only.'],
  },
  {
    scientificModelId: 'grim_age',
    componentRole: 'research_only',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: 'grimage/1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['Mortality-trained methylation surrogate age is not authorized for production combination.'],
  },
  {
    scientificModelId: 'frailty_index',
    componentRole: 'interpretive_context',
    outputConstruct: 'proportion',
    outputUnit: 'proportion',
    currentModelVersion: 'frailty-index/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Frailty may be reported as its own validated construct but cannot alter age in years.'],
  },
  {
    scientificModelId: 'vo2max_normative_ageing',
    componentRole: 'normative_context',
    outputConstruct: 'percentile',
    outputUnit: 'percentile',
    currentModelVersion: 'friend-vo2max/context-1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: [
      'Direct measured VO2max may support protocol-specific normative context.',
      'No conversion to years or validated composite contribution exists.',
    ],
  },
  {
    scientificModelId: 'hrv_derived_age',
    componentRole: 'monitoring_signal',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'hrv-derived-age/unsupported-1.0.0',
    currentAvailability: 'rejected',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Generic HRV-derived age is rejected; source-attributed HRV may remain a Recovery monitoring signal.'],
  },
  {
    scientificModelId: 'resting_heart_rate_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'resting-heart-rate/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Resting heart rate retains physiologic context and has no validated age transformation.'],
  },
  {
    scientificModelId: 'sleep_duration_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'sleep-duration/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Sleep duration is interpretive context and cannot add or subtract biological-age years.'],
  },
  {
    scientificModelId: 'sleep_consistency_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'sleep-regularity/research-1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['Sleep regularity remains research context with no validated age conversion.'],
  },
  {
    scientificModelId: 'cardiorespiratory_fitness_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'crf-literature/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Outcome associations support interpretation, not an age conversion.'],
  },
  {
    scientificModelId: 'nutrition_longevity_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'none',
    currentModelVersion: 'nutrition-longevity/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Nutrition evidence may support domain interpretation but not biological-age influence.'],
  },
  {
    scientificModelId: 'inflammation_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'context_only',
    outputUnit: 'source_unit',
    currentModelVersion: 'inflammation/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Inflammation context overlaps CRP and WBC inputs already represented inside Clinical PhenoAge.'],
  },
  {
    scientificModelId: 'cardiometabolic_risk_literature',
    componentRole: 'interpretive_context',
    outputConstruct: 'risk_estimate',
    outputUnit: 'probability',
    currentModelVersion: 'cardiometabolic-risk/context-1.0.0',
    currentAvailability: 'context_only',
    combinationStatus: 'ineligible',
    numericAgeInfluence: 'prohibited',
    rationale: ['Cardiometabolic risk is a distinct construct and cannot be treated as biological age.'],
  },
  {
    scientificModelId: 'cardiometage',
    componentRole: 'research_only',
    outputConstruct: 'age_in_years',
    outputUnit: 'years',
    currentModelVersion: 'cardiometage/research-1.0.0',
    currentAvailability: 'research_only',
    combinationStatus: 'research_only',
    numericAgeInfluence: 'prohibited',
    rationale: ['Independent replication, implementation audit, and overlap review are incomplete.'],
  },
] as const satisfies readonly ScientificModelComponentMapping[];

/**
 * Domain signals remain outside the component-combination path unless a future
 * versioned scientific model explicitly requires them.
 */
export const DOMAIN_CONTEXT_ROLE_MAPPINGS = [
  { id: 'sleep_duration', label: 'Sleep duration', scientificModelId: 'sleep_duration_literature', primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Sleep duration may support explanation but has no age-in-years transformation.' },
  { id: 'sleep_regularity', label: 'Sleep regularity', scientificModelId: 'sleep_consistency_literature', primaryRole: 'interpretive_context', secondaryRoles: ['monitoring_signal'], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Regularity remains source-attributed context and research monitoring.' },
  { id: 'hrv', label: 'Heart-rate variability', scientificModelId: 'hrv_derived_age', primaryRole: 'monitoring_signal', secondaryRoles: ['interpretive_context'], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'HRV can be monitored in Recovery but generic HRV-derived age is rejected.' },
  { id: 'resting_heart_rate', label: 'Resting heart rate', scientificModelId: 'resting_heart_rate_literature', primaryRole: 'interpretive_context', secondaryRoles: ['monitoring_signal'], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Resting heart rate is physiologic context, not an age conversion.' },
  { id: 'smoking', label: 'Smoking', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Exposure and risk context must not add or subtract years without a validated model.' },
  { id: 'alcohol', label: 'Alcohol', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Behavioral context cannot numerically alter an age result.' },
  { id: 'nutrition', label: 'Nutrition', scientificModelId: 'nutrition_longevity_literature', primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Nutrition supports domain interpretation only.' },
  { id: 'medication', label: 'Medication', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Medication remains context unless an independently validated model explicitly requires it.' },
  { id: 'supplement', label: 'Supplement', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Supplement use is not a biological-age modifier.' },
  { id: 'peptide', label: 'Peptide', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Peptide use is context only and cannot imply effectiveness.' },
  { id: 'therapy', label: 'Therapy', scientificModelId: null, primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'Therapy context cannot be interpreted as treatment effect or age change.' },
  { id: 'frailty', label: 'Frailty', scientificModelId: 'frailty_index', primaryRole: 'interpretive_context', secondaryRoles: [], numericAgeInfluence: 'prohibited', combinationStatus: 'ineligible', rationale: 'A validated Frailty Index remains separately reported and does not alter age.' },
] as const satisfies readonly DomainContextRoleMapping[];

export const CURRENT_MULTIMODAL_PRODUCT_TRUTH = {
  validatedProductionAgeModels: ['clinical-phenoage/1.0.0'],
  productionLabel: 'Blood-Based Phenotypic Age',
  multimodalBiologicalAgeExists: false,
  policy: 'Clinical PhenoAge v1.0.0 is the only validated production age model. Domain signals do not alter its output.',
} as const;
