import type { EvidenceReferenceId } from '../models';
import { defineArchitectureFit, defineCandidateRisks, defineCandidateRubric } from './builders';
import type { ScientificCandidateDossier } from './contracts';

const CARDIOMETAGE_EVIDENCE = ['li_cardiometage_2026'] as const satisfies readonly EvidenceReferenceId[];
const FRAILTY_EVIDENCE = ['searle_frailty_2008'] as const satisfies readonly EvidenceReferenceId[];
const HRV_EVIDENCE = ['nunan_hrv_2010', 'garavaglia_hrv_2021'] as const satisfies readonly EvidenceReferenceId[];
const SLEEP_EVIDENCE = ['cappuccio_sleep_2010', 'windred_sleep_regularity_2024'] as const satisfies readonly EvidenceReferenceId[];

export const CARDIOMETAGE_CANDIDATE_DOSSIER = {
  id: 'cardiometage', title: 'CardioMetAge', scientificModelIds: ['cardiometage', 'cardiometabolic_risk_literature'], referenceOnly: false,
  evidenceReferenceIds: CARDIOMETAGE_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'Cardiometabolic aging and disease-outcome risk from chronological age and common clinical biomarkers.',
    scientificConstruct: 'Cardiometabolic-focused age-equivalent model with disease-outcome calibration.',
    requiredInputs: ['Chronological age', 'Published clinical biomarker panel', 'Exact units and assay context', 'Validated model version'],
    typicalUse: ['Cardiometabolic aging research', 'Disease incidence and mortality association research'],
    knownStrengths: ['Common clinical inputs', 'Age-in-years output', 'Large development and application datasets', 'Cardiometabolic outcome focus'],
    knownLimitations: ['Very recent model', 'No independent replication yet established', 'Substantial blood-input and outcome overlap risk', 'Disease-risk focus may be confused with general biological age'],
    validationHistory: ['Developed in NHANES III', 'Applied to later NHANES and UK Biobank in the primary publication'],
    currentResearchStatus: 'Emerging 2026 model awaiting independent replication and implementation audit.',
    productionReadinessSummary: 'Requires independent review; not ready for implementation.',
    expectedFutureStability: 'Unknown until independent teams reproduce the exact model and version.',
    importantAssumptions: ['Cardiometabolic outcome calibration transports', 'Published biomarkers and units are reproduced exactly'],
    knownControversies: ['Outcome-focused age may represent disease risk more than general aging', 'Intervention-change interpretation requires independent evidence'],
    missingEvidence: ['Independent replication', 'Test-retest evidence', 'Incremental value and overlap versus Clinical PhenoAge', 'Population subgroup validation'],
    populationLimitations: ['NHANES and UK Biobank anchoring', 'International and subgroup transportability are unknown'],
    measurementBurden: 'moderate', costImplications: 'moderate', clinicalAvailability: 'common',
  },
  rubric: defineCandidateRubric(CARDIOMETAGE_EVIDENCE, {
    scientific_evidence_quality: ['moderate', 'The primary study is substantial but remains one model-development report.'],
    external_validation: ['moderate', 'Application cohorts were reported by the developing study rather than independent teams.'],
    independent_replication: ['insufficient', 'No independent reproduction is established.'],
    population_diversity: ['moderate', 'NHANES and UK Biobank provide scale but limited global diversity.'],
    clinical_relevance: ['moderate', 'Cardiometabolic outcomes are relevant but model use is not clinically established.'],
    longevity_relevance: ['moderate', 'It captures cardiometabolic aging rather than whole-person aging.'],
    construct_clarity: ['moderate', 'Disease-focused age requires careful distinction from general biological age.'],
    interpretability: ['moderate', 'Clinical inputs are interpretable; outcome calibration can be overstated.'],
    input_reliability: ['moderate', 'Common biomarkers can be reliable under exact assay policies.'],
    measurement_availability: ['strong', 'Inputs appear clinically accessible.'],
    standardization: ['unknown', 'Independent implementation and assay robustness are not established.'],
    implementation_complexity: ['limited', 'Exact independent reproduction has not been completed.'],
    maintenance_burden: ['unknown', 'Version and surveillance needs are not mature.'],
    calibration_availability: ['limited', 'One published calibration exists without independent production audit.'],
    version_stability: ['unknown', 'The model is too new to assess drift or revision stability.'],
    temporal_robustness: ['unknown', 'Repeatability and longitudinal treatment meaning are not established independently.'],
    generalizability: ['limited', 'Transport beyond reported datasets is uncertain.'],
    risk_of_misuse: ['limited', 'Cardiometabolic risk may be presented as general biological age or treatment response.'],
    double_counting_risk: ['insufficient', 'Clinical biomarkers and cardiometabolic outcomes substantially overlap Clinical PhenoAge.'],
    correlation_with_production_model: ['insufficient', 'Shared blood physiology and NHANES derivation imply material correlation risk.'],
    architecture_compatibility: ['moderate', 'Contracts fit, but no eligibility, calculation verification, or authorization exists.'],
    multimodal_suitability: ['limited', 'It may add specialization rather than independent modality.'],
    expert_review_need: ['insufficient', 'Independent statistical, clinical, and implementation review is absent.'],
    future_calibration_need: ['unknown', 'Population-specific recalibration requirements are not yet known.'],
    additional_governance_need: ['limited', 'Disease-risk, intervention, overlap, and version governance are unresolved.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'The emerging model and related risk literature are registered.'],
    eligibility_engine: ['blocked', 'No versioned input policy is approved.'],
    execution_authorization: ['blocked', 'Research-only model cannot execute.'],
    versioning: ['compatible_with_conditions', 'Exact version can be governed after independent audit.'],
    scientific_governance: ['compatible_with_conditions', 'Lifecycle support exists; evidence review is incomplete.'],
    component_contracts: ['compatible_with_conditions', 'It remains Research Only until construct role is independently resolved.'],
    temporal_policies: ['blocked', 'No validated freshness or repeat-measurement policy exists.'],
    uncertainty_architecture: ['compatible', 'Outcome, population, measurement, and overlap uncertainty can be retained.'],
    combination_safety: ['blocked', 'Blood and outcome overlap with Clinical PhenoAge are unresolved.'],
    presentation_layer: ['blocked', 'No safe production meaning is approved.'],
    multimodal_framework: ['blocked', 'Independent contribution is not demonstrated.'],
    living_sphere: ['not_applicable', 'No renderer integration is allowed.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['high', 'The model is new and independently unreplicated.', 'Wait for independent cohorts and exact reproduction.'],
    implementation_risk: ['high', 'Premature implementation could lock an unstable model.', 'Do not implement before verification.'],
    maintenance_risk: ['unknown', 'Revision cadence is unknown.', 'Establish ownership only after model stability emerges.'],
    future_migration_risk: ['high', 'Early revisions may be non-comparable.', 'Use research-only immutable versions.'],
    regulatory_ambiguity: ['high', 'Disease-risk age may be clinically interpreted.', 'Require regulatory review.'],
    clinical_interpretation_risk: ['high', 'Users may infer cardiometabolic diagnosis.', 'Keep research-only.'],
    user_misunderstanding_risk: ['high', 'A specialized age may be mistaken for whole-person age.', 'Use construct-specific terminology.'],
    biological_age_overstatement_risk: ['high', 'Disease-specific calibration can be overgeneralized.', 'Prohibit general age claims.'],
    unsupported_marketing_risk: ['high', 'Novelty and intervention findings are easy to overmarket.', 'Require replication before claims.'],
    double_counting_risk: ['high', 'Shared biomarkers and outcomes overlap production.', 'Complete full overlap audit.'],
    population_transportability_risk: ['high', 'Reported populations do not establish universal transport.', 'Require independent subgroup evidence.'],
    version_drift_risk: ['unknown', 'No history exists to assess stability.', 'Monitor literature without implementing.'],
  }),
  implementationReadiness: 'requires_independent_review',
  readinessReasons: ['Promising primary evidence but no independent replication.', 'High overlap with Clinical PhenoAge.', 'Version and temporal stability are unknown.'],
  priorityTier: 'tier_3',
  priorityRationale: ['Monitor as an emerging specialized model.', 'Do not prioritize ahead of KDM calibration or independently governed VO₂max context.'],
  recommendedAction: 'Retain as research-only and reopen evaluation after independent replication and overlap analysis.',
  governancePrerequisites: ['Independent replication', 'Exact implementation audit', 'Input and outcome overlap review', 'Population transportability review', 'Version-stability evidence'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const FRAILTY_CANDIDATE_DOSSIER = {
  id: 'frailty_index', title: 'Deficit-Accumulation Frailty Index', scientificModelIds: ['frailty_index'], referenceOnly: false,
  evidenceReferenceIds: FRAILTY_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'The proportion of predefined health deficits accumulated by an individual.',
    scientificConstruct: 'Frailty and vulnerability, reported as a proportion rather than age in years.',
    requiredInputs: ['A validated deficit set', 'Consistent deficit coding', 'Adequate completeness', 'Population-appropriate assessment'],
    typicalUse: ['Geriatric assessment', 'Population frailty research', 'Outcome-risk context'],
    knownStrengths: ['Standard construction principles', 'Broad replication', 'Clinical interpretability in older adults', 'Strong outcome associations'],
    knownLimitations: ['Deficit sets vary', 'Less informative in younger low-deficit populations', 'Can include disease and disability consequences', 'Not biological age in years'],
    validationHistory: ['Standard procedure demonstrated in older cohorts', 'Extensive subsequent clinical and population use'],
    currentResearchStatus: 'Established frailty construct, not a biological-age model for Vitalspan.',
    productionReadinessSummary: 'Potentially suitable as a separate context construct; not recommended as an age component.',
    expectedFutureStability: 'Strong when a validated deficit set and coding version are fixed.',
    importantAssumptions: ['Deficits cover multiple systems', 'Missingness and coding follow a validated procedure', 'Target population is appropriate'],
    knownControversies: ['Different deficit sets can produce similar aggregate properties but differ clinically', 'Frailty and biological age should not be conflated'],
    missingEvidence: ['Validated value for younger Vitalspan populations', 'Any justified contribution to multimodal age'],
    populationLimitations: ['Evidence is strongest in older adults'],
    measurementBurden: 'high', costImplications: 'moderate', clinicalAvailability: 'specialty',
  },
  rubric: defineCandidateRubric(FRAILTY_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'Frailty Index construction and outcome associations are well established.'],
    external_validation: ['strong', 'The construct is used across many cohorts.'],
    independent_replication: ['strong', 'Deficit-accumulation properties are widely replicated.'],
    population_diversity: ['moderate', 'Use is broad but strongest among older populations.'],
    clinical_relevance: ['strong', 'Frailty has established geriatric meaning.'],
    longevity_relevance: ['moderate', 'Frailty relates to vulnerability and outcomes, not age itself.'],
    construct_clarity: ['excellent', 'Deficit proportion is distinct from age in years.'],
    interpretability: ['strong', 'Deficits and completeness can be explained directly.'],
    input_reliability: ['moderate', 'Reliability depends on deficit selection and coding.'],
    measurement_availability: ['moderate', 'A comprehensive validated deficit set requires broad assessment.'],
    standardization: ['moderate', 'Construction rules exist, but item sets vary.'],
    implementation_complexity: ['moderate', 'A population-appropriate deficit set requires substantial design and validation.'],
    maintenance_burden: ['moderate', 'Item definitions and completeness policies need versioning.'],
    calibration_availability: ['limited', 'No Vitalspan-specific validated deficit set exists.'],
    version_stability: ['strong', 'A frozen deficit set can be stable.'],
    temporal_robustness: ['moderate', 'Repeated frailty can be meaningful with consistent assessment.'],
    generalizability: ['limited', 'Younger populations often have floor effects.'],
    risk_of_misuse: ['moderate', 'Risk is controlled if it remains explicitly frailty.'],
    double_counting_risk: ['limited', 'Deficits can include diseases and functions represented elsewhere.'],
    correlation_with_production_model: ['moderate', 'Health burden may correlate without sharing the same construct.'],
    architecture_compatibility: ['strong', 'Context and proportion contracts can represent it safely.'],
    multimodal_suitability: ['limited', 'It should remain separately reported context.'],
    expert_review_need: ['moderate', 'Geriatric and measurement review is required for any product deficit set.'],
    future_calibration_need: ['limited', 'A target-population deficit set must be validated.'],
    additional_governance_need: ['moderate', 'Item-set versioning and population applicability require governance.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'Frailty Index is registered as Context Only.'],
    eligibility_engine: ['blocked', 'No product deficit-set input policy exists.'],
    execution_authorization: ['not_applicable', 'It is not authorized as an age calculation.'],
    versioning: ['compatible_with_conditions', 'A fixed deficit set and coding policy would require a version.'],
    scientific_governance: ['compatible', 'The lifecycle can govern a separate context construct.'],
    component_contracts: ['compatible', 'Interpretive Context permits a separately reported proportion.'],
    temporal_policies: ['compatible_with_conditions', 'Repeat assessment requires consistent item availability.'],
    uncertainty_architecture: ['compatible', 'Missing deficits, population fit, and measurement uncertainty remain explicit.'],
    combination_safety: ['blocked', 'Frailty must not numerically alter age.'],
    presentation_layer: ['compatible_with_conditions', 'Future presentation must say Frailty Index, not age.'],
    multimodal_framework: ['compatible_with_conditions', 'May coexist as context only.'],
    living_sphere: ['not_applicable', 'No renderer change is authorized.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'Construct is strong but target-population applicability varies.', 'Validate a population-appropriate deficit set.'],
    implementation_risk: ['moderate', 'Poor item selection can create an invalid index.', 'Use geriatric and measurement review.'],
    maintenance_risk: ['moderate', 'Deficit definitions may change.', 'Version item sets.'],
    future_migration_risk: ['moderate', 'Changing items reduces comparability.', 'Preserve historical versions.'],
    regulatory_ambiguity: ['moderate', 'Frailty may be clinically interpreted.', 'Keep descriptive, non-diagnostic boundaries.'],
    clinical_interpretation_risk: ['moderate', 'Meaning differs by population and completeness.', 'Expose missingness and limitations.'],
    user_misunderstanding_risk: ['moderate', 'Users may conflate frailty with biological age.', 'Use separate construct naming.'],
    biological_age_overstatement_risk: ['high', 'Converting deficit proportion to years is unsupported.', 'Prohibit conversion.'],
    unsupported_marketing_risk: ['moderate', 'Frailty improvement could be overstated.', 'Avoid treatment-effect claims.'],
    double_counting_risk: ['high', 'Deficits may duplicate diseases and domain evidence.', 'Audit every deficit against other components.'],
    population_transportability_risk: ['high', 'Younger users may have floor effects.', 'Restrict unsupported populations.'],
    version_drift_risk: ['moderate', 'Item sets can drift while retaining the same label.', 'Bind outputs to exact deficit-set versions.'],
  }),
  implementationReadiness: 'not_recommended',
  readinessReasons: ['Scientifically valid frailty construct, but not a biological-age model.', 'Vitalspan lacks a validated population-appropriate deficit set.'],
  priorityTier: 'tier_3',
  priorityRationale: ['Potential future context value, especially for older populations.', 'Should never compete with or modify age estimates.'],
  recommendedAction: 'Keep Frailty Index separate; consider only as a future validated context module.',
  governancePrerequisites: ['Define target population', 'Select and validate deficit set', 'Version coding and completeness policy', 'Prohibit age conversion and cross-domain double counting'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const HRV_BIOLOGICAL_AGE_CANDIDATE_DOSSIER = {
  id: 'hrv_biological_age', title: 'HRV-based biological-age models', scientificModelIds: ['hrv_derived_age'], referenceOnly: false,
  evidenceReferenceIds: HRV_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'Proposed age-like transformations from heart-rate variability or autonomic measurements.',
    scientificConstruct: 'No canonical validated biological-age construct; HRV remains a monitoring signal.',
    requiredInputs: ['Protocol-specific ECG-quality HRV', 'Artifact processing', 'Posture, breathing, time, medication, rhythm, and device context', 'Validated population reference'],
    typicalUse: ['Autonomic monitoring', 'Recovery observation', 'Age-association research'],
    knownStrengths: ['Noninvasive', 'Repeatable in principle', 'Large-scale wearable collection is possible'],
    knownLimitations: ['High protocol and device dependence', 'Large interindividual variation', 'Medication and fitness confounding', 'No canonical validated age transformation'],
    validationHistory: ['Normative and association literature exists', 'Method heterogeneity prevents one accepted age model'],
    currentResearchStatus: 'Useful monitoring evidence; generic HRV biological age is scientifically rejected.',
    productionReadinessSummary: 'Rejected as an age model; retain only source-attributed Recovery context.',
    expectedFutureStability: 'Unknown because device, protocol, and algorithm definitions continue to vary.',
    importantAssumptions: ['Device accuracy and artifact control', 'Comparable recording context', 'No unsupported age conversion'],
    knownControversies: ['Wearable vendors may produce proprietary age/readiness labels without independent validation'],
    missingEvidence: ['Canonical model', 'Independent validation', 'Cross-device calibration', 'Clinical and longevity construct validation'],
    populationLimitations: ['Age, sex, fitness, medication, rhythm, and health status alter distributions'],
    measurementBurden: 'low', costImplications: 'moderate', clinicalAvailability: 'common',
  },
  rubric: defineCandidateRubric(HRV_EVIDENCE, {
    scientific_evidence_quality: ['limited', 'Age associations exist, but no validated biological-age model is established.'],
    external_validation: ['insufficient', 'There is no canonical model to validate externally.'],
    independent_replication: ['insufficient', 'Methods and outputs are heterogeneous.'],
    population_diversity: ['limited', 'Norms vary materially across populations and protocols.'],
    clinical_relevance: ['moderate', 'HRV has monitoring relevance but not age-model utility.'],
    longevity_relevance: ['limited', 'Association evidence does not validate biological age.'],
    construct_clarity: ['insufficient', '“HRV age” lacks one agreed scientific construct.'],
    interpretability: ['limited', 'HRV is explainable; proprietary transformations are not.'],
    input_reliability: ['limited', 'Reliability is device and protocol dependent.'],
    measurement_availability: ['strong', 'Wearable HRV is widely available.'],
    standardization: ['insufficient', 'Recording, artifact, metric, and device standards are inconsistent.'],
    implementation_complexity: ['limited', 'A simple transformation would be scientifically unjustified; a valid model is unavailable.'],
    maintenance_burden: ['insufficient', 'Device and firmware changes would require continuous calibration.'],
    calibration_availability: ['insufficient', 'No approved calibration exists.'],
    version_stability: ['insufficient', 'Proprietary algorithms and devices drift.'],
    temporal_robustness: ['limited', 'HRV changes with acute state and recording conditions.'],
    generalizability: ['insufficient', 'Protocol and population effects prevent broad transport.'],
    risk_of_misuse: ['insufficient', 'Recovery fluctuations can be mislabeled aging or danger.'],
    double_counting_risk: ['limited', 'HRV overlaps Recovery, fitness, medication, and lifestyle context.'],
    correlation_with_production_model: ['unknown', 'No stable model exists for assessment.'],
    architecture_compatibility: ['strong', 'Monitoring Signal contracts fit; age-model execution does not.'],
    multimodal_suitability: ['insufficient', 'No validated numerical contribution exists.'],
    expert_review_need: ['insufficient', 'A future model would require device, autonomic, statistical, and clinical review.'],
    future_calibration_need: ['insufficient', 'Device- and protocol-specific calibration would be unavoidable.'],
    additional_governance_need: ['insufficient', 'Device surveillance and marketing-risk governance would be extensive.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'Generic HRV-derived age is explicitly Rejected.'],
    eligibility_engine: ['blocked', 'Unsupported version cannot become eligible.'],
    execution_authorization: ['blocked', 'Rejected models cannot execute.'],
    versioning: ['blocked', 'No canonical scientific model version exists.'],
    scientific_governance: ['compatible', 'The rejection and any future reevaluation can be governed.'],
    component_contracts: ['compatible', 'Monitoring Signal preserves HRV without age influence.'],
    temporal_policies: ['compatible_with_conditions', 'Recovery monitoring can use domain history, not age conversion.'],
    uncertainty_architecture: ['compatible', 'Device, measurement, temporal, and population uncertainty are explicit.'],
    combination_safety: ['blocked', 'HRV cannot enter age combination.'],
    presentation_layer: ['blocked', 'No HRV-age presentation is scientifically allowed.'],
    multimodal_framework: ['blocked', 'Only contextual coexistence is permitted.'],
    living_sphere: ['not_applicable', 'Existing Recovery visual influence is not a biological-age contribution.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['high', 'No canonical validated age construct exists.', 'Reject age implementation.'],
    implementation_risk: ['high', 'A convenient transformation would invent science.', 'Retain only raw/domain interpretation.'],
    maintenance_risk: ['high', 'Devices and algorithms drift continuously.', 'Keep source provenance in Recovery.'],
    future_migration_risk: ['high', 'Vendor changes break comparability.', 'Never persist generic HRV age.'],
    regulatory_ambiguity: ['moderate', 'Age and readiness labels may imply clinical meaning.', 'Avoid such labels.'],
    clinical_interpretation_risk: ['high', 'Acute autonomic change may be misread as aging.', 'Separate monitoring from age.'],
    user_misunderstanding_risk: ['high', 'Daily age changes would appear biologically meaningful.', 'Prohibit age output.'],
    biological_age_overstatement_risk: ['high', 'HRV alone cannot represent biological age.', 'Maintain rejection.'],
    unsupported_marketing_risk: ['high', 'Wearable age is commercially tempting.', 'Require independent model evidence before reevaluation.'],
    double_counting_risk: ['high', 'It overlaps Recovery, Fitness, Lifestyle, and Medication signals.', 'Keep domain-local.'],
    population_transportability_risk: ['high', 'Norms vary by many user characteristics.', 'Do not generalize.'],
    version_drift_risk: ['high', 'Device algorithms and firmware are unstable.', 'Preserve device provenance only.'],
  }),
  implementationReadiness: 'rejected',
  readinessReasons: ['No canonical independently validated biological-age model.', 'Severe device, protocol, and confounding dependence.', 'Monitoring value does not justify age conversion.'],
  priorityTier: 'rejected',
  priorityRationale: ['Should not enter Vitalspan as biological age.', 'HRV remains valuable inside Recovery monitoring.'],
  recommendedAction: 'Exclude wearable-derived HRV age; retain HRV only as source-attributed monitoring and interpretation.',
  governancePrerequisites: ['A wholly new peer-reviewed canonical model', 'Independent cross-device validation', 'Population and protocol calibration', 'Clinical and regulatory review'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const SLEEP_BIOLOGICAL_AGE_CANDIDATE_DOSSIER = {
  id: 'sleep_biological_age', title: 'Sleep-derived biological-age models', scientificModelIds: ['sleep_duration_literature', 'sleep_consistency_literature'], referenceOnly: false,
  evidenceReferenceIds: SLEEP_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'Proposed age-like estimates derived from sleep duration, regularity, staging, or nocturnal physiology.',
    scientificConstruct: 'Emerging heterogeneous risk or chronological-age prediction; no validated canonical biological-age model.',
    requiredInputs: ['Model-specific sleep signals', 'Validated sleep-state inference or polysomnography', 'Sufficient observation window', 'Device and protocol provenance'],
    typicalUse: ['Sleep monitoring', 'Risk association research', 'Emerging machine-learning age prediction'],
    knownStrengths: ['Noninvasive repeated evidence', 'Sleep regularity and duration have outcome associations', 'Potential longitudinal context'],
    knownLimitations: ['Observational confounding and reverse causation', 'Device and algorithm dependence', 'No canonical age model', 'Sleep need and measurement vary by person'],
    validationHistory: ['Duration meta-analysis and objective regularity cohorts support context', 'Emerging age-prediction studies do not define one production model'],
    currentResearchStatus: 'Context and emerging research only.',
    productionReadinessSummary: 'Not recommended as biological age; retain Sleep domain interpretation.',
    expectedFutureStability: 'Unknown because inputs, devices, and model targets vary.',
    importantAssumptions: ['Sleep measurement is valid', 'Observation windows are sufficient', 'Risk or chronological-age prediction is not mislabeled aging'],
    knownControversies: ['U-shaped outcome associations do not imply age conversion', 'Machine-learning age gaps may reflect disease mix or dataset bias'],
    missingEvidence: ['Canonical construct', 'Independent multi-device replication', 'Prospective biological-age validation', 'Clinical utility'],
    populationLimitations: ['Much evidence comes from middle-aged and older cohorts', 'Sleep norms differ by age, health, culture, and work schedules'],
    measurementBurden: 'low', costImplications: 'moderate', clinicalAvailability: 'common',
  },
  rubric: defineCandidateRubric(SLEEP_EVIDENCE, {
    scientific_evidence_quality: ['moderate', 'Sleep-health associations are strong; biological-age modeling evidence is not.'],
    external_validation: ['limited', 'Context associations replicate, while age models remain heterogeneous.'],
    independent_replication: ['insufficient', 'No single canonical sleep-age model has independent replication.'],
    population_diversity: ['limited', 'Evidence is concentrated in selected adult cohorts.'],
    clinical_relevance: ['moderate', 'Sleep assessment is clinically relevant, but age output is not.'],
    longevity_relevance: ['moderate', 'Sleep relates to outcomes without defining aging rate or age.'],
    construct_clarity: ['insufficient', 'Sleep-derived age can mean chronological-age prediction, risk, or disease burden.'],
    interpretability: ['limited', 'Raw sleep metrics are interpretable; derived age models are often opaque.'],
    input_reliability: ['limited', 'Wearable and polysomnographic sleep measures are not interchangeable.'],
    measurement_availability: ['strong', 'Consumer sleep data are widely available.'],
    standardization: ['insufficient', 'Devices, staging, windows, and algorithms vary.'],
    implementation_complexity: ['limited', 'A scientifically valid canonical implementation is unavailable.'],
    maintenance_burden: ['insufficient', 'Device and inference algorithms drift.'],
    calibration_availability: ['insufficient', 'No approved model calibration exists.'],
    version_stability: ['insufficient', 'No stable canonical version exists.'],
    temporal_robustness: ['moderate', 'Repeated sleep can be monitored, but age meaning is unvalidated.'],
    generalizability: ['limited', 'Sleep patterns and device performance vary across populations.'],
    risk_of_misuse: ['insufficient', 'Nightly changes could be presented as aging or treatment response.'],
    double_counting_risk: ['limited', 'Sleep overlaps Lifestyle, Recovery, HRV, medication, and disease context.'],
    correlation_with_production_model: ['unknown', 'No stable candidate model exists.'],
    architecture_compatibility: ['strong', 'Interpretive Context and Monitoring Signal roles fit safely.'],
    multimodal_suitability: ['insufficient', 'No validated numerical contribution exists.'],
    expert_review_need: ['insufficient', 'Sleep medicine, device, statistics, and clinical review would be required.'],
    future_calibration_need: ['insufficient', 'Device and population calibration are unresolved.'],
    additional_governance_need: ['insufficient', 'Device, temporal, marketing, and model-surveillance governance would be extensive.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible_with_conditions', 'Duration and regularity literature are registered; no canonical sleep-age model exists.'],
    eligibility_engine: ['blocked', 'No production sleep-age version or input policy exists.'],
    execution_authorization: ['blocked', 'Context and research literature cannot authorize age calculation.'],
    versioning: ['blocked', 'No canonical model version exists.'],
    scientific_governance: ['compatible', 'Future evidence can enter the lifecycle without changing architecture.'],
    component_contracts: ['compatible', 'Sleep remains Interpretive Context or Monitoring Signal.'],
    temporal_policies: ['compatible_with_conditions', 'Domain trend windows remain separate from age eligibility.'],
    uncertainty_architecture: ['compatible', 'Device, temporal, population, and construct uncertainty are preserved.'],
    combination_safety: ['blocked', 'Sleep cannot numerically alter age.'],
    presentation_layer: ['blocked', 'No sleep-age presentation is authorized.'],
    multimodal_framework: ['blocked', 'Only contextual coexistence is supported.'],
    living_sphere: ['not_applicable', 'Sleep may influence its existing visual domain layer, not biological age.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['high', 'No canonical validated biological-age construct exists.', 'Retain contextual interpretation only.'],
    implementation_risk: ['high', 'A model choice would be speculative.', 'Wait for independent canonical evidence.'],
    maintenance_risk: ['high', 'Devices and algorithms change.', 'Keep device provenance and domain-local models.'],
    future_migration_risk: ['high', 'Vendor model changes break history.', 'Do not persist sleep age.'],
    regulatory_ambiguity: ['moderate', 'Sleep risk and age claims can imply medical assessment.', 'Use bounded observation language.'],
    clinical_interpretation_risk: ['high', 'Sleep disorders or illness could dominate predictions.', 'Do not infer age or diagnosis.'],
    user_misunderstanding_risk: ['high', 'Nightly variability may appear as rapid aging.', 'Prohibit dynamic age labels.'],
    biological_age_overstatement_risk: ['high', 'Sleep alone cannot represent biological age.', 'Keep separate domain interpretation.'],
    unsupported_marketing_risk: ['high', 'Wearable sleep age is marketable without validated meaning.', 'Require independent evidence before reconsideration.'],
    double_counting_risk: ['high', 'Sleep overlaps HRV, Recovery, Lifestyle, and medication effects.', 'Keep domains independent.'],
    population_transportability_risk: ['high', 'Sleep norms and devices vary substantially.', 'Avoid global age models.'],
    version_drift_risk: ['high', 'Sleep inference algorithms are frequently revised.', 'Retain source and version provenance.'],
  }),
  implementationReadiness: 'not_recommended',
  readinessReasons: ['No canonical independently validated sleep-derived biological-age model.', 'Existing evidence supports interpretation and monitoring, not age conversion.'],
  priorityTier: 'research',
  priorityRationale: ['Monitor emerging literature without product implementation.', 'Sleep remains valuable inside Domain Intelligence and Trend Intelligence.'],
  recommendedAction: 'Do not implement sleep-derived biological age; retain deterministic Sleep context and monitoring.',
  governancePrerequisites: ['A canonical peer-reviewed construct', 'Independent multi-device validation', 'Temporal and population calibration', 'Clinical utility and misuse review'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const CONTEXT_CANDIDATE_DOSSIERS = [
  CARDIOMETAGE_CANDIDATE_DOSSIER,
  FRAILTY_CANDIDATE_DOSSIER,
  HRV_BIOLOGICAL_AGE_CANDIDATE_DOSSIER,
  SLEEP_BIOLOGICAL_AGE_CANDIDATE_DOSSIER,
] as const satisfies readonly ScientificCandidateDossier[];
