import type { EvidenceReferenceId } from '../models';
import { defineArchitectureFit, defineCandidateRisks, defineCandidateRubric } from './builders';
import type { ScientificCandidateDossier } from './contracts';

const DUNEDIN_EVIDENCE = ['belsky_dunedinpace_2022'] as const satisfies readonly EvidenceReferenceId[];
const DNAM_PHENOAGE_EVIDENCE = ['levine_phenoage_2018'] as const satisfies readonly EvidenceReferenceId[];
const GRIMAGE_EVIDENCE = ['lu_grimage_2019'] as const satisfies readonly EvidenceReferenceId[];

export const DUNEDINPACE_CANDIDATE_DOSSIER = {
  id: 'dunedinpace', title: 'DunedinPACE', scientificModelIds: ['dunedinpace'], referenceOnly: false,
  evidenceReferenceIds: DUNEDIN_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'A DNA-methylation proxy for longitudinal pace of physiological change distilled into a blood assay.',
    scientificConstruct: 'Pace per biological year, not age in years.',
    requiredInputs: ['Whole-blood DNA methylation', 'Compatible array and preprocessing', 'Official probe and normalization requirements', 'Quality-controlled specimen'],
    typicalUse: ['Geroscience research', 'Longitudinal and intervention research', 'Association with morbidity, disability, and mortality'],
    knownStrengths: ['Training target used repeated organ-system measures over two decades', 'High reported test-retest reliability', 'Evaluated in additional datasets', 'Construct is explicitly pace'],
    knownLimitations: ['Single 1972–1973 New Zealand birth cohort anchored the training target', 'Specialized assay and preprocessing', 'Single assay estimates a longitudinally trained construct', 'Clinical utility is not established'],
    validationHistory: ['Developed from four waves of organ-system data', 'Evaluated in five additional datasets', 'Reported associations with functional and mortality outcomes'],
    currentResearchStatus: 'Active geroscience biomarker with research use and specialized laboratory dependencies.',
    productionReadinessSummary: 'Research only without laboratory access, licensed/official implementation review, and independent product validation.',
    expectedFutureStability: 'Moderate if assay platform, preprocessing, probe handling, and algorithm version are fixed.',
    importantAssumptions: ['Methylation preprocessing matches the validated pipeline', 'The longitudinal training construct transports to the user population', 'Pace remains distinct from age'],
    knownControversies: ['Intervention sensitivity does not itself establish clinical treatment monitoring', 'Population and assay transportability remain debated'],
    missingEvidence: ['Vitalspan-compatible laboratory integration', 'Clinical decision utility', 'Prospective validation of any joint use with age-in-years models'],
    populationLimitations: ['Training target derived from one birth cohort', 'External datasets do not erase target-population constraints'],
    measurementBurden: 'very_high', costImplications: 'very_high', clinicalAvailability: 'research_only',
  },
  rubric: defineCandidateRubric(DUNEDIN_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'The pace target is longitudinal and the primary model is peer reviewed.'],
    external_validation: ['strong', 'The primary study evaluated multiple additional datasets.'],
    independent_replication: ['moderate', 'External applications exist, but implementation and assay dependencies remain material.'],
    population_diversity: ['limited', 'The training target comes from one narrow birth cohort.'],
    clinical_relevance: ['limited', 'Research relevance is strong; clinical meaning and actionability are not established.'],
    longevity_relevance: ['strong', 'The target explicitly captures longitudinal multi-system change.'],
    construct_clarity: ['excellent', 'Pace per biological year is distinct from age in years.'],
    interpretability: ['moderate', 'Construct meaning is clear, while methylation feature contribution is not clinically intuitive.'],
    input_reliability: ['moderate', 'Reported reliability is high under compatible assay and preprocessing.'],
    measurement_availability: ['insufficient', 'Vitalspan has no production methylation laboratory access.'],
    standardization: ['limited', 'Array, normalization, probe quality, and licensing require strict control.'],
    implementation_complexity: ['insufficient', 'Laboratory, preprocessing, and verification work is substantial.'],
    maintenance_burden: ['limited', 'Platform, preprocessing, licensing, and reference implementation require surveillance.'],
    calibration_availability: ['limited', 'An official research implementation exists, but production authorization and laboratory calibration do not.'],
    version_stability: ['moderate', 'A frozen version is possible if all external dependencies are locked.'],
    temporal_robustness: ['strong', 'The construct is based on longitudinal training, although a single assay produces the proxy.'],
    generalizability: ['limited', 'Training population and assay transport remain important limitations.'],
    risk_of_misuse: ['limited', 'Pace can be mistaken for annual treatment effect or age acceleration in years.'],
    double_counting_risk: ['moderate', 'No direct blood-panel duplication, but shared aging outcomes and physiology may correlate.'],
    correlation_with_production_model: ['moderate', 'It is a distinct modality and construct but likely correlated through common outcomes.'],
    architecture_compatibility: ['moderate', 'Pace contracts fit, but current eligibility and laboratory dependencies are absent.'],
    multimodal_suitability: ['limited', 'Pace should remain parallel and cannot be averaged with age in years.'],
    expert_review_need: ['insufficient', 'Independent epigenetics, laboratory, licensing, and clinical review is incomplete.'],
    future_calibration_need: ['limited', 'Assay and population calibration may be required for production use.'],
    additional_governance_need: ['limited', 'Licensing, assay version, repeatability, and intervention-claim governance are unresolved.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'DunedinPACE is registered as a distinct pace model.'],
    eligibility_engine: ['blocked', 'No production input policy or assay eligibility implementation exists.'],
    execution_authorization: ['blocked', 'Research-only version cannot receive production execution authorization.'],
    versioning: ['compatible_with_conditions', 'Exact algorithm, assay, and preprocessing versions must coexist.'],
    scientific_governance: ['compatible_with_conditions', 'The lifecycle can govern it, but review remains early.'],
    component_contracts: ['compatible', 'Pace-of-Aging Measure preserves its native construct.'],
    temporal_policies: ['compatible_with_conditions', 'Repeat and intervention interpretation require model-specific policy.'],
    uncertainty_architecture: ['compatible', 'Assay, population, temporal, and model uncertainties remain separable.'],
    combination_safety: ['blocked', 'Pace is construct-incompatible with age-in-years combination.'],
    presentation_layer: ['blocked', 'No production result or approved pace presentation exists.'],
    multimodal_framework: ['compatible_with_conditions', 'May remain parallel context; no numerical synthesis is authorized.'],
    living_sphere: ['not_applicable', 'No renderer or motion change is scientifically authorized.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'The construct is scientifically coherent but population and proxy limitations remain.', 'Retain pace-specific limitations and provenance.'],
    implementation_risk: ['high', 'Assay and preprocessing mismatch can change the output.', 'Require an audited laboratory and locked reference pipeline.'],
    maintenance_risk: ['high', 'Array platforms, preprocessing, and licensing evolve.', 'Version every dependency and revalidate changes.'],
    future_migration_risk: ['high', 'Platform changes may break comparability.', 'Never silently migrate historical results.'],
    regulatory_ambiguity: ['high', 'Pace may be marketed as intervention response.', 'Require explicit non-treatment and non-diagnostic governance.'],
    clinical_interpretation_risk: ['high', 'Clinical thresholds and actionability are not established.', 'Keep research-only until clinical review.'],
    user_misunderstanding_risk: ['high', 'Users may convert pace into years gained or lost.', 'Prohibit age conversion and annualized promises.'],
    biological_age_overstatement_risk: ['high', 'One methylation pace proxy is not whole-person age.', 'Use exact construct naming.'],
    unsupported_marketing_risk: ['high', 'Intervention sensitivity claims are commercially attractive.', 'Require source-level claim review.'],
    double_counting_risk: ['moderate', 'Outcome and physiology overlap require review despite different inputs.', 'Retain outcome correlation metadata.'],
    population_transportability_risk: ['high', 'The training target is population-specific.', 'Require direct applicability evidence.'],
    version_drift_risk: ['high', 'Assay and algorithm variants can diverge.', 'Lock algorithm, probes, platform, preprocessing, and license version.'],
  }),
  implementationReadiness: 'research_only',
  readinessReasons: ['Strong pace science does not make it an age-in-years model.', 'Vitalspan lacks validated methylation laboratory access.', 'Clinical and intervention interpretation remain unresolved.'],
  priorityTier: 'research',
  priorityRationale: ['Scientifically valuable but should remain an independent research construct.', 'It does not answer the need for a second compatible age-in-years model.'],
  recommendedAction: 'Keep DunedinPACE independent as pace; do not combine or convert it, and defer implementation until laboratory and governance prerequisites exist.',
  governancePrerequisites: ['Validated laboratory access', 'Exact assay and preprocessing version', 'Independent implementation verification', 'Population applicability review', 'Licensing review', 'Pace-specific presentation and intervention-claim governance'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const DNAM_PHENOAGE_CANDIDATE_DOSSIER = {
  id: 'dnam_phenoage', title: 'DNAm PhenoAge', scientificModelIds: ['dnam_phenoage'], referenceOnly: false,
  evidenceReferenceIds: DNAM_PHENOAGE_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'A DNA-methylation predictor trained to approximate clinical Phenotypic Age and associated aging outcomes.',
    scientificConstruct: 'Epigenetic surrogate age in years whose training target is closely related to Clinical PhenoAge.',
    requiredInputs: ['Whole-blood DNA methylation', 'Compatible methylation platform', 'Validated preprocessing', 'Published CpG model', 'Cell-composition and batch handling'],
    typicalUse: ['Epigenetic aging research', 'Age-acceleration association studies', 'Cross-tissue and outcome studies'],
    knownStrengths: ['Peer-reviewed fixed model', 'Age-in-years output', 'Associations with aging-related outcomes', 'Different measurement modality from clinical blood chemistry'],
    knownLimitations: ['Specialized assay', 'Batch and cell-composition effects', 'Clinical utility is not established', 'Training target creates construct dependence on clinical PhenoAge'],
    validationHistory: ['Developed and tested across several cohorts and tissues in the primary model work', 'Widely used in research cohorts'],
    currentResearchStatus: 'Established research epigenetic clock without Vitalspan laboratory infrastructure.',
    productionReadinessSummary: 'Requires independent review and laboratory integration; not suitable without actual assay access.',
    expectedFutureStability: 'Moderate if the exact platform, preprocessing, and model implementation are frozen.',
    importantAssumptions: ['Assay and preprocessing reproduce the validated model', 'Blood methylation is appropriate for intended interpretation', 'The surrogate target adds value beyond Clinical PhenoAge'],
    knownControversies: ['Epigenetic clocks measure different constructs despite similar year units', 'Age acceleration may reflect early-life and social exposures as well as current physiology'],
    missingEvidence: ['Incremental independence from Clinical PhenoAge for Vitalspan', 'Production laboratory reproducibility', 'Clinical actionability', 'Prospective composite validation'],
    populationLimitations: ['Cohort and ancestry representation varies', 'Batch and tissue effects limit transportability'],
    measurementBurden: 'very_high', costImplications: 'very_high', clinicalAvailability: 'research_only',
  },
  rubric: defineCandidateRubric(DNAM_PHENOAGE_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'The model is peer reviewed with outcome-oriented development.'],
    external_validation: ['strong', 'It has broad research application across cohorts.'],
    independent_replication: ['moderate', 'Many applications exist, but pipeline heterogeneity affects exact reproducibility.'],
    population_diversity: ['moderate', 'Multiple cohorts exist, with incomplete subgroup transportability.'],
    clinical_relevance: ['limited', 'Clinical use and actionable interpretation are not established.'],
    longevity_relevance: ['strong', 'The model was designed around phenotypic aging and aging outcomes.'],
    construct_clarity: ['moderate', 'Year units are clear, but the output is a methylation surrogate of a clinical target.'],
    interpretability: ['limited', 'CpG features and preprocessing are less interpretable than clinical inputs.'],
    input_reliability: ['moderate', 'Reliability depends on assay, batch correction, cell composition, and pipeline.'],
    measurement_availability: ['insufficient', 'No Vitalspan methylation laboratory path exists.'],
    standardization: ['limited', 'Platform and preprocessing differences can affect output.'],
    implementation_complexity: ['insufficient', 'Laboratory, bioinformatics, licensing, and validation are substantial.'],
    maintenance_burden: ['limited', 'Platform and pipeline surveillance is ongoing.'],
    calibration_availability: ['limited', 'Published model exists, but production calibration and pipeline authorization do not.'],
    version_stability: ['moderate', 'A frozen implementation is possible with controlled external dependencies.'],
    temporal_robustness: ['limited', 'Cross-sectional assay does not automatically establish pace or treatment effect.'],
    generalizability: ['moderate', 'Research replication is broad but not universal.'],
    risk_of_misuse: ['limited', 'Epigenetic age is often interpreted as definitive or reversible whole-person age.'],
    double_counting_risk: ['insufficient', 'The training target directly depends on clinical Phenotypic Age.'],
    correlation_with_production_model: ['insufficient', 'Construct correlation is expected because Clinical PhenoAge informed the training target.'],
    architecture_compatibility: ['moderate', 'Contracts fit, but eligibility, assay, and authorization do not exist.'],
    multimodal_suitability: ['limited', 'Different modality does not ensure independent construct information.'],
    expert_review_need: ['insufficient', 'Epigenetics, laboratory, bioinformatics, licensing, and clinical reviews are incomplete.'],
    future_calibration_need: ['limited', 'Platform and population calibration may be necessary.'],
    additional_governance_need: ['limited', 'Assay, preprocessing, licensing, and claims governance are substantial.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'DNAm PhenoAge has a separate canonical registry identity.'],
    eligibility_engine: ['blocked', 'No assay-specific input policy or production eligibility exists.'],
    execution_authorization: ['blocked', 'The registered version is research-only.'],
    versioning: ['compatible_with_conditions', 'Model, platform, preprocessing, and CpG handling require exact versions.'],
    scientific_governance: ['compatible_with_conditions', 'The lifecycle can govern it, but expert review is incomplete.'],
    component_contracts: ['compatible_with_conditions', 'It identifies age in years but currently remains Research Only.'],
    temporal_policies: ['compatible_with_conditions', 'Specimen and repeat-measurement policies need validation.'],
    uncertainty_architecture: ['compatible', 'Assay, population, model, and correlation uncertainties can remain explicit.'],
    combination_safety: ['blocked', 'Training-target overlap with Clinical PhenoAge is unresolved.'],
    presentation_layer: ['blocked', 'No authorized scientific result or differentiation policy exists.'],
    multimodal_framework: ['compatible_with_conditions', 'Could be evaluated later, but modality independence does not establish construct independence.'],
    living_sphere: ['not_applicable', 'No renderer change is within scope.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'Evidence is strong but construct dependence and clinical meaning remain uncertain.', 'Retain explicit surrogate-target provenance.'],
    implementation_risk: ['high', 'Assay and pipeline errors can silently change results.', 'Require independently verified end-to-end laboratory fixtures.'],
    maintenance_risk: ['high', 'Platforms, preprocessing, and licensing evolve.', 'Version every external dependency.'],
    future_migration_risk: ['high', 'Array or preprocessing changes may break comparability.', 'Do not mutate existing versions.'],
    regulatory_ambiguity: ['high', 'Consumer epigenetic age claims may imply clinical utility.', 'Complete regulatory and claims review.'],
    clinical_interpretation_risk: ['high', 'No validated treatment decisions follow from the output.', 'Use research-only limitations.'],
    user_misunderstanding_risk: ['high', 'Epigenetic branding can imply definitive biological truth.', 'Explain surrogate construct and assay uncertainty.'],
    biological_age_overstatement_risk: ['high', 'Year units invite whole-person interpretation.', 'Keep model-specific name and prohibit multimodal labels.'],
    unsupported_marketing_risk: ['high', 'Reversal and intervention claims are common risks.', 'Require evidence-linked claim approval.'],
    double_counting_risk: ['high', 'The model was trained on a Clinical PhenoAge-related target.', 'Require explicit target-overlap review.'],
    population_transportability_risk: ['moderate', 'Cohort and ancestry performance may differ.', 'Block unsupported populations.'],
    version_drift_risk: ['high', 'Pipeline variants can share a name while differing scientifically.', 'Use full assay and preprocessing version identity.'],
  }),
  implementationReadiness: 'requires_independent_review',
  readinessReasons: ['Strong research candidate but not accessible without validated methylation laboratory infrastructure.', 'Training-target overlap limits independence from Clinical PhenoAge.', 'Clinical utility and product reproducibility are unverified.'],
  priorityTier: 'tier_2',
  priorityRationale: ['Potential future age-in-years modality after laboratory access exists.', 'Lower immediate feasibility and independence than a named KDM calibration.'],
  recommendedAction: 'Do not implement without laboratory access; first audit end-to-end assay reproducibility and incremental independence from Clinical PhenoAge.',
  governancePrerequisites: ['Validated laboratory partnership', 'Locked assay and preprocessing', 'Independent implementation fixtures', 'Licensing review', 'Population validation', 'Target-overlap and incremental-value review'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const GRIMAGE_CANDIDATE_DOSSIER = {
  id: 'grim_age', title: 'DNAm GrimAge', scientificModelIds: ['grim_age'], referenceOnly: false,
  evidenceReferenceIds: GRIMAGE_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'A DNA-methylation surrogate age trained from smoking and plasma-protein surrogates associated with mortality.',
    scientificConstruct: 'Mortality-risk surrogate age in years, not a direct mechanistic or whole-person age.',
    requiredInputs: ['Whole-blood DNA methylation', 'Validated preprocessing', 'Published surrogate model dependencies', 'Chronological age and sex where specified'],
    typicalUse: ['Mortality and morbidity association research', 'Epigenetic age-acceleration studies'],
    knownStrengths: ['Strong reported outcome associations', 'Peer-reviewed model structure', 'Multiple validation cohorts'],
    knownLimitations: ['Smoking is embedded', 'Specialized assay and preprocessing', 'Risk-surrogate construct', 'Clinical actionability is not established'],
    validationHistory: ['Developed with training and test partitions', 'Evaluated across multiple cohorts and outcomes'],
    currentResearchStatus: 'Established research clock with strong mortality associations and high misuse risk.',
    productionReadinessSummary: 'Research only; not suitable without methylation access and careful risk-versus-age governance.',
    expectedFutureStability: 'Moderate with frozen assay and algorithm, but external pipeline dependencies remain.',
    importantAssumptions: ['Methylation surrogates reproduce intended protein and smoking signals', 'Risk-surrogate age is not interpreted as lifespan'],
    knownControversies: ['Strong outcome prediction may reflect embedded risk factors rather than a general aging construct', 'Smoking contribution complicates combination with lifestyle context'],
    missingEvidence: ['Clinical utility', 'Vitalspan assay reproducibility', 'Safe incremental role beyond Clinical PhenoAge and smoking context'],
    populationLimitations: ['Cohort and assay transportability', 'Embedded smoking relationships may vary'],
    measurementBurden: 'very_high', costImplications: 'very_high', clinicalAvailability: 'research_only',
  },
  rubric: defineCandidateRubric(GRIMAGE_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'Primary development and validation are substantial.'],
    external_validation: ['strong', 'Multiple validation cohorts support outcome associations.'],
    independent_replication: ['moderate', 'Research use is broad, while pipeline reproducibility remains relevant.'],
    population_diversity: ['moderate', 'Several cohorts exist but universal transportability is not established.'],
    clinical_relevance: ['limited', 'Risk prediction associations do not create clinical treatment utility.'],
    longevity_relevance: ['strong', 'The model is strongly associated with mortality and morbidity outcomes.'],
    construct_clarity: ['moderate', 'It is a mortality-risk surrogate age, which can be confused with biological age.'],
    interpretability: ['limited', 'Embedded methylation surrogates and smoking reduce transparency.'],
    input_reliability: ['moderate', 'Reliability depends on exact assay and preprocessing.'],
    measurement_availability: ['insufficient', 'Vitalspan lacks methylation laboratory access.'],
    standardization: ['limited', 'Platform and preprocessing require tight governance.'],
    implementation_complexity: ['insufficient', 'Laboratory and model-pipeline implementation is substantial.'],
    maintenance_burden: ['limited', 'Assay, model, and licensing dependencies require surveillance.'],
    calibration_availability: ['limited', 'Published model exists; production pipeline and calibration do not.'],
    version_stability: ['moderate', 'A frozen version is possible with controlled dependencies.'],
    temporal_robustness: ['limited', 'Cross-sectional age acceleration cannot be assumed to measure treatment response.'],
    generalizability: ['moderate', 'Outcome replication exists but population effects remain.'],
    risk_of_misuse: ['insufficient', 'Mortality-trained age can be mistaken for life expectancy or disease prediction.'],
    double_counting_risk: ['limited', 'Mortality outcomes and embedded smoking overlap existing model and Lifestyle context.'],
    correlation_with_production_model: ['limited', 'Both are mortality-calibrated, increasing outcome-level correlation risk.'],
    architecture_compatibility: ['moderate', 'Research contracts fit; no production eligibility or assay boundary exists.'],
    multimodal_suitability: ['limited', 'Outcome and smoking overlap undermine clean independence.'],
    expert_review_need: ['insufficient', 'Epigenetic, risk-model, regulatory, and laboratory review is incomplete.'],
    future_calibration_need: ['limited', 'Assay and population calibration may be required.'],
    additional_governance_need: ['insufficient', 'Mortality, smoking, marketing, assay, and combination governance are substantial.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'GrimAge is registered separately as mortality-risk surrogate age.'],
    eligibility_engine: ['blocked', 'No production input policy exists.'],
    execution_authorization: ['blocked', 'The registered model remains research-only.'],
    versioning: ['compatible_with_conditions', 'Exact assay, preprocessing, and model version are required.'],
    scientific_governance: ['compatible_with_conditions', 'Lifecycle support exists but risk review is incomplete.'],
    component_contracts: ['compatible_with_conditions', 'Research Only preserves the risk-surrogate construct.'],
    temporal_policies: ['compatible_with_conditions', 'Repeat interpretation requires dedicated evidence.'],
    uncertainty_architecture: ['compatible', 'Risk, smoking, assay, population, and temporal uncertainty can remain explicit.'],
    combination_safety: ['blocked', 'Mortality and smoking overlap are unresolved.'],
    presentation_layer: ['blocked', 'No safe product meaning is approved.'],
    multimodal_framework: ['blocked', 'Current evidence does not support combining it with Clinical PhenoAge.'],
    living_sphere: ['not_applicable', 'No visual integration is authorized.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'Strong outcome prediction does not define a general aging construct.', 'Label mortality-risk surrogate explicitly.'],
    implementation_risk: ['high', 'Assay and surrogate pipeline are complex.', 'Require end-to-end independent validation.'],
    maintenance_risk: ['high', 'External platform and algorithm dependencies persist.', 'Version all dependencies.'],
    future_migration_risk: ['high', 'Pipeline changes can break comparability.', 'Retain immutable historical versions.'],
    regulatory_ambiguity: ['high', 'Mortality-related output may be regulated or interpreted as risk prediction.', 'Require regulatory review before any product use.'],
    clinical_interpretation_risk: ['high', 'Users may infer disease or mortality prognosis.', 'Keep research-only and prohibit clinical claims.'],
    user_misunderstanding_risk: ['high', 'The name invites lifespan and age interpretation.', 'Explain surrogate risk construct if ever presented.'],
    biological_age_overstatement_risk: ['high', 'Mortality association can be overstated as biological truth.', 'Do not label whole-person age.'],
    unsupported_marketing_risk: ['high', 'Mortality and longevity claims carry exceptional misuse potential.', 'Require strict claim prohibition.'],
    double_counting_risk: ['high', 'Mortality and smoking evidence overlaps production and Lifestyle context.', 'Require outcome and exposure overlap review.'],
    population_transportability_risk: ['moderate', 'Cohort and smoking-pattern differences matter.', 'Require subgroup validation.'],
    version_drift_risk: ['high', 'Model and methylation pipeline variants may diverge.', 'Use complete version identity.'],
  }),
  implementationReadiness: 'research_only',
  readinessReasons: ['Strong research outcome associations are offset by risk-surrogate meaning, assay burden, and extreme misuse risk.', 'No product laboratory or eligibility path exists.'],
  priorityTier: 'research',
  priorityRationale: ['Lower architectural independence and higher misuse risk than DNAm PhenoAge.', 'Does not currently strengthen product scientific integrity enough to justify implementation.'],
  recommendedAction: 'Retain in the research registry; do not implement for product use.',
  governancePrerequisites: ['Validated laboratory and pipeline', 'Independent implementation review', 'Mortality-risk and regulatory review', 'Smoking and outcome-overlap review', 'Explicit non-lifespan presentation policy'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const METHYLATION_CANDIDATE_DOSSIERS = [
  DUNEDINPACE_CANDIDATE_DOSSIER,
  DNAM_PHENOAGE_CANDIDATE_DOSSIER,
  GRIMAGE_CANDIDATE_DOSSIER,
] as const satisfies readonly ScientificCandidateDossier[];
