import type { EvidenceReferenceId } from '../models';
import { defineArchitectureFit, defineCandidateRisks, defineCandidateRubric } from './builders';
import type { ScientificCandidateDossier } from './contracts';

const PHENOAGE_EVIDENCE = [
  'levine_phenoage_2018', 'liu_phenoage_validation_2018',
] as const satisfies readonly EvidenceReferenceId[];

const KDM_EVIDENCE = [
  'klemera_doubal_2006', 'levine_kdm_2013',
] as const satisfies readonly EvidenceReferenceId[];

const VO2MAX_EVIDENCE = [
  'kaminsky_friend_2015', 'mandsager_crf_2018',
] as const satisfies readonly EvidenceReferenceId[];

export const CLINICAL_PHENOAGE_REFERENCE_DOSSIER = {
  id: 'clinical_phenoage_reference',
  title: 'Clinical PhenoAge v1.0.0 — production reference',
  scientificModelIds: ['clinical_phenoage'],
  referenceOnly: true,
  evidenceReferenceIds: PHENOAGE_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'Mortality-calibrated physiological dysregulation from chronological age and nine clinical blood measurements.',
    scientificConstruct: 'Cross-sectional Blood-Based Phenotypic Age expressed in age-equivalent years.',
    requiredInputs: ['Chronological age', 'Albumin', 'Creatinine', 'Glucose', 'CRP', 'Lymphocyte percentage', 'MCV', 'RDW', 'Alkaline phosphatase', 'White blood cell count'],
    typicalUse: ['Research biomarker of phenotypic aging', 'Mortality and morbidity association studies', 'Vitalspan production blood-age reference'],
    knownStrengths: ['Fixed published input set', 'Common clinical measurements', 'External outcome validation', 'Versioned and independently verified Vitalspan implementation'],
    knownLimitations: ['Mortality-calibrated rather than a direct aging-mechanism measurement', 'Chronological age is an input', 'One visit cannot measure pace', 'Acute illness and assay context can affect results'],
    validationHistory: ['Developed from NHANES III clinical evidence', 'Validated in NHANES IV and additional cohorts', 'Vitalspan v1.0.0 independently reproduced against locked fixtures'],
    currentResearchStatus: 'Established research model and sole validated Vitalspan production age model.',
    productionReadinessSummary: 'Production ready only as the existing model-specific Blood-Based Phenotypic Age implementation.',
    expectedFutureStability: 'High when coefficients, normalization, eligibility, and version remain frozen.',
    importantAssumptions: ['Exact input identity and units', 'Supported adult population', 'Compatible single laboratory context'],
    knownControversies: ['Age-equivalent output may be misunderstood as whole-person age', 'Mortality calibration is not equivalent to a mechanistic aging measure'],
    missingEvidence: ['Prospective validation of any future multimodal combination', 'Universal population transportability'],
    populationLimitations: ['NHANES-derived populations', 'Subgroup calibration and transportability remain incomplete'],
    measurementBurden: 'moderate',
    costImplications: 'moderate',
    clinicalAvailability: 'common',
  },
  rubric: defineCandidateRubric(PHENOAGE_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'The fixed clinical model has peer-reviewed derivation and outcome validation.'],
    external_validation: ['strong', 'External cohort validation exists, although transportability is not universal.'],
    independent_replication: ['strong', 'Published replications and Vitalspan independent fixtures support reproducibility.'],
    population_diversity: ['moderate', 'Multiple cohorts exist, but derivation remains anchored to United States population data.'],
    clinical_relevance: ['moderate', 'Inputs are clinically familiar; the age-equivalent construct is not a diagnosis.'],
    longevity_relevance: ['strong', 'The model was trained against mortality-related phenotypic evidence.'],
    construct_clarity: ['strong', 'Blood-based mortality-calibrated phenotypic age is explicit and bounded.'],
    interpretability: ['strong', 'All inputs, provenance, limitations, and authorization are auditable.'],
    input_reliability: ['strong', 'Standard laboratory inputs can be measured reliably with compatible assays.'],
    measurement_availability: ['strong', 'The required blood panel is commonly obtainable.'],
    standardization: ['strong', 'Vitalspan has a locked unit, eligibility, and normalization contract.'],
    implementation_complexity: ['strong', 'The existing implementation is versioned, validated, and operational.'],
    maintenance_burden: ['moderate', 'Assay drift, population evidence, and version governance require surveillance.'],
    calibration_availability: ['excellent', 'The production version has a fixed published calibration.'],
    version_stability: ['strong', 'Version 1.0.0 has locked coefficients, fixtures, and fingerprints.'],
    temporal_robustness: ['limited', 'Cross-sectional output does not establish longitudinal pace or treatment effect.'],
    generalizability: ['moderate', 'External evidence exists but unsupported populations must remain excluded.'],
    risk_of_misuse: ['limited', 'Age-in-years presentation carries material whole-person and treatment-effect misunderstanding risk.'],
    double_counting_risk: ['limited', 'Its blood inputs overlap likely cardiometabolic, inflammation, renal, and hematologic candidates.'],
    correlation_with_production_model: ['not_applicable', 'This is the production reference itself.'],
    architecture_compatibility: ['excellent', 'Registry, eligibility, authorization, version, and typed product boundaries are complete.'],
    multimodal_suitability: ['limited', 'One validated model is not multimodal and no composite validation exists.'],
    expert_review_need: ['strong', 'Independent validation is complete for v1.0.0; ongoing scientific governance remains required.'],
    future_calibration_need: ['moderate', 'New populations or scientific behavior would require a new reviewed version.'],
    additional_governance_need: ['moderate', 'Combination and population-expansion governance remain unimplemented.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'Canonical model, aliases, evidence, and version are registered.'],
    eligibility_engine: ['compatible', 'Production eligibility is implemented and fail-closed.'],
    execution_authorization: ['compatible', 'Exact evidence is bound to short-lived execution authorization.'],
    versioning: ['compatible', 'Clinical PhenoAge v1.0.0 is explicit and immutable.'],
    scientific_governance: ['compatible', 'Independent verification and production cutover are documented.'],
    component_contracts: ['compatible', 'It maps to Primary Age Estimate.'],
    temporal_policies: ['compatible_with_conditions', 'Single-collection policy is supported; cross-model alignment is undefined.'],
    uncertainty_architecture: ['compatible', 'Eligibility and component uncertainty can retain separate provenance.'],
    combination_safety: ['blocked', 'No second compatible model or combination authorization exists.'],
    presentation_layer: ['compatible', 'Current typed adapter presents model-specific output without changing science.'],
    multimodal_framework: ['compatible_with_conditions', 'It can participate only as one independent component after future compatibility approval.'],
    living_sphere: ['not_applicable', 'The Living Sphere remains independent and must not display this as multimodal age.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'The construct is validated but not a direct measure of aging mechanisms.', 'Retain model-specific naming and limitations.'],
    implementation_risk: ['low', 'The locked implementation is already independently validated.', 'Preserve fingerprints and golden fixtures.'],
    maintenance_risk: ['moderate', 'Laboratory and evidence drift require surveillance.', 'Use immutable versions and periodic scientific review.'],
    future_migration_risk: ['moderate', 'A future version may not be comparable in place.', 'Require new versions and migration documentation.'],
    regulatory_ambiguity: ['moderate', 'Age-equivalent output can be interpreted clinically.', 'Maintain non-diagnostic claims and legal review.'],
    clinical_interpretation_risk: ['high', 'Users may infer disease or treatment meaning.', 'Keep deterministic limitations and unavailable states visible.'],
    user_misunderstanding_risk: ['high', 'Years are intuitively interpreted as whole-person age.', 'Always label Blood-Based Phenotypic Age.'],
    biological_age_overstatement_risk: ['high', 'One blood model cannot represent whole-person biological age.', 'Prohibit multimodal or whole-person labels.'],
    unsupported_marketing_risk: ['high', 'Longevity marketing could overstate a mortality-calibrated biomarker.', 'Require claim governance and source review.'],
    double_counting_risk: ['high', 'Multiple candidate models reuse its inputs and outcomes.', 'Use explicit overlap profiles and combination review.'],
    population_transportability_risk: ['moderate', 'Calibration may not transport uniformly.', 'Block unsupported populations and version extensions.'],
    version_drift_risk: ['low', 'The production version is fingerprinted.', 'Reject silent formula or normalization changes.'],
  }),
  implementationReadiness: 'production_ready',
  readinessReasons: ['Already independently validated and deployed as the single authorized model-specific calculation.', 'Reference-only in this evaluation; no scientific change is proposed.'],
  priorityTier: 'reference_only',
  priorityRationale: ['It is the baseline against which independence, overlap, and added scientific value must be judged.'],
  recommendedAction: 'Maintain v1.0.0 unchanged as Blood-Based Phenotypic Age and retain its regression locks.',
  governancePrerequisites: ['No new implementation action', 'Continue version, evidence, population, and marketing surveillance'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const KDM_CANDIDATE_DOSSIER = {
  id: 'kdm',
  title: 'Klemera–Doubal Method — named calibration required',
  scientificModelIds: ['kdm_biological_age', 'levine_2013_kdm'],
  referenceOnly: false,
  evidenceReferenceIds: KDM_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'A calibration-dependent latent biological-age estimate from age-associated biomarkers.',
    scientificConstruct: 'Age-equivalent estimate whose definition depends on the selected biomarkers, population calibration, and KDM implementation.',
    requiredInputs: ['Chronological age where specified', 'Calibration-specific biomarker panel', 'Reference-population slopes and residual variation', 'Exact sex or population stratification where specified'],
    typicalUse: ['Population aging research', 'Mortality and disability association studies', 'Comparison of biological-age algorithms'],
    knownStrengths: ['Explicit statistical framework', 'Age-in-years construct', 'Published precision framework', 'Can use clinically available measurements'],
    knownLimitations: ['KDM is a method rather than one universal model', 'Outputs vary with biomarker panel and calibration population', 'Often overlaps Clinical PhenoAge inputs', 'Historical calibrations may not transport'],
    validationHistory: ['Method described and simulated in 2006', 'NHANES III implementation compared with other algorithms in 2013', 'Subsequent cohort applications use heterogeneous calibrations'],
    currentResearchStatus: 'Scientifically established method with no named Vitalspan production calibration.',
    productionReadinessSummary: 'Not production ready; selection and independent validation of one immutable calibration are mandatory.',
    expectedFutureStability: 'Potentially stable only after a named calibration, reference population, and biomarker panel are frozen.',
    importantAssumptions: ['Calibration biomarkers retain age relationships in the target population', 'Reference residual structure is appropriate', 'Measurement protocols match calibration evidence'],
    knownControversies: ['Different KDM implementations are often discussed as if they were one model', 'Chronological age inclusion and calibration choices change interpretation'],
    missingEvidence: ['A selected modern calibration for Vitalspan', 'Independent implementation verification', 'Prospective incremental value beyond Clinical PhenoAge', 'Formal overlap and combination review'],
    populationLimitations: ['Every calibration is population-specific', 'Historical NHANES implementations may not generalize internationally'],
    measurementBurden: 'moderate',
    costImplications: 'moderate',
    clinicalAvailability: 'common',
  },
  rubric: defineCandidateRubric(KDM_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'The method and a historically important implementation are peer reviewed.'],
    external_validation: ['moderate', 'Multiple applications exist but are not one consistent calibrated model.'],
    independent_replication: ['moderate', 'The method is replicated, while exact implementations and panels vary.'],
    population_diversity: ['limited', 'Calibration-specific populations prevent assuming broad transportability.'],
    clinical_relevance: ['moderate', 'Clinical biomarkers are interpretable, but the latent age estimate is not diagnostic.'],
    longevity_relevance: ['strong', 'KDM was developed explicitly as a biological-age method and has mortality associations.'],
    construct_clarity: ['moderate', 'The method is clear, but “KDM age” is ambiguous without a calibration name.'],
    interpretability: ['moderate', 'Inputs are explainable; calibration dependence and precision require careful explanation.'],
    input_reliability: ['moderate', 'Reliability depends entirely on the selected clinical panel and assay compatibility.'],
    measurement_availability: ['strong', 'A clinical KDM panel can use routinely available measurements.'],
    standardization: ['limited', 'No universal biomarker set or reference calibration exists.'],
    implementation_complexity: ['limited', 'Exact calibration, stratification, covariance, and validation choices create substantial complexity.'],
    maintenance_burden: ['limited', 'Population and assay drift require calibration-specific surveillance.'],
    calibration_availability: ['insufficient', 'No named production calibration is approved for Vitalspan.'],
    version_stability: ['limited', 'Stability is impossible until one immutable calibration is selected.'],
    temporal_robustness: ['limited', 'Most applications are cross-sectional and do not establish pace or treatment response.'],
    generalizability: ['limited', 'Transportability must be established independently for each calibration.'],
    risk_of_misuse: ['limited', 'A generic “KDM age” label hides calibration dependence.'],
    double_counting_risk: ['limited', 'Likely clinical panels overlap Clinical PhenoAge physiology and biomarkers.'],
    correlation_with_production_model: ['limited', 'Clinical-biomarker overlap may produce correlated rather than independent information.'],
    architecture_compatibility: ['strong', 'The registry and eligibility architecture already support a future named version.'],
    multimodal_suitability: ['moderate', 'A validated calibration could provide a second age estimate, but independence is unproven.'],
    expert_review_need: ['insufficient', 'No calibration-specific statistical, laboratory, and clinical review is complete.'],
    future_calibration_need: ['insufficient', 'Calibration is a prerequisite, not an optional enhancement.'],
    additional_governance_need: ['limited', 'Calibration ownership, surveillance, overlap, and retirement policies remain undefined.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible_with_conditions', 'Generic KDM and historical Levine KDM records exist; a named calibration needs its own versioned record.'],
    eligibility_engine: ['compatible_with_conditions', 'A calibration-aware policy exists conceptually but cannot authorize an unconfigured model.'],
    execution_authorization: ['blocked', 'No calculation implementation or calibration-specific evidence binding exists.'],
    versioning: ['blocked', 'The unconfigured placeholder is not a scientific production version.'],
    scientific_governance: ['compatible_with_conditions', 'The lifecycle can govern calibration selection but required reviews are incomplete.'],
    component_contracts: ['compatible', 'It maps to a future Independent Age Estimate.'],
    temporal_policies: ['compatible_with_conditions', 'A selected calibration must define collection and repeat-measurement behavior.'],
    uncertainty_architecture: ['compatible', 'Calibration, population, measurement, and overlap uncertainties can remain separate.'],
    combination_safety: ['blocked', 'Incremental independence and double counting versus Clinical PhenoAge are unresolved.'],
    presentation_layer: ['blocked', 'No unambiguous calibrated model name or authorized result exists.'],
    multimodal_framework: ['compatible_with_conditions', 'Could enter future compatibility review only after independent validation.'],
    living_sphere: ['not_applicable', 'No Living Sphere behavior should change during scientific evaluation.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['high', 'Generic KDM does not identify one scientific model.', 'Select and audit one named calibration before implementation.'],
    implementation_risk: ['high', 'Substituting calibration inputs would silently create a different model.', 'Lock exact inputs, parameters, population, and independent fixtures.'],
    maintenance_risk: ['high', 'Calibration transport and assay drift require continuing review.', 'Assign calibration ownership and revalidation cadence.'],
    future_migration_risk: ['high', 'Changing a panel or population creates non-comparable results.', 'Require a new component and model version for every calibration change.'],
    regulatory_ambiguity: ['moderate', 'Age-in-years output may appear clinically authoritative.', 'Bound claims and retain non-diagnostic language.'],
    clinical_interpretation_risk: ['high', 'Users may not understand calibration dependence.', 'Include calibration name, population, uncertainty, and limitations.'],
    user_misunderstanding_risk: ['high', 'A second age may imply a more accurate whole-person truth.', 'Present independent model identity and never average automatically.'],
    biological_age_overstatement_risk: ['high', 'KDM can be overstated as universal biological age.', 'Prohibit generic KDM and whole-person labels.'],
    unsupported_marketing_risk: ['high', 'The method name can be used without specifying calibration.', 'Require scientific claim approval tied to exact version.'],
    double_counting_risk: ['high', 'Likely panels overlap blood physiology in Clinical PhenoAge.', 'Complete biomarker, outcome, and correlation review.'],
    population_transportability_risk: ['high', 'Calibration validity is population-dependent.', 'Block populations without direct validation.'],
    version_drift_risk: ['high', 'Multiple published KDM variants can be conflated.', 'Use immutable named calibration identifiers.'],
  }),
  implementationReadiness: 'requires_calibration',
  readinessReasons: ['Highest-value next age-model candidate because it is an explicit age construct with potentially accessible inputs.', 'No generic KDM calculation is scientifically permissible.', 'A named calibration and independent incremental-value review are missing.'],
  priorityTier: 'tier_1',
  priorityRationale: ['Best candidate for the next formal implementation program, not immediate production execution.', 'Its clinical-input feasibility is higher than methylation models.', 'Calibration dependence and overlap must be resolved before any code phase.'],
  recommendedAction: 'Begin a calibration-selection and independent scientific-review phase; do not implement a calculator yet.',
  governancePrerequisites: ['Select one named peer-reviewed calibration', 'Audit exact inputs and population', 'Establish calibration licensing and availability', 'Independently reproduce reference results', 'Demonstrate incremental value and evaluate overlap with Clinical PhenoAge', 'Approve a versioned input policy'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const VO2MAX_CANDIDATE_DOSSIER = {
  id: 'vo2max',
  title: 'Direct measured VO₂max — normative context candidate',
  scientificModelIds: ['vo2max_normative_ageing', 'cardiorespiratory_fitness_literature'],
  referenceOnly: false,
  evidenceReferenceIds: VO2MAX_EVIDENCE,
  evidenceProfile: {
    whatItMeasures: 'Maximal cardiorespiratory fitness under a defined exercise-testing protocol.',
    scientificConstruct: 'Direct physiological capacity and population-specific normative position, not biological age in years.',
    requiredInputs: ['Direct maximal CPET VO₂ measurement', 'Age', 'Sex or validated stratifiers', 'Body-size normalization where specified', 'Exercise modality and quality criteria', 'Versioned normative reference'],
    typicalUse: ['Exercise physiology', 'Clinical functional assessment', 'Risk stratification', 'Normative fitness context'],
    knownStrengths: ['Objective physiological capacity', 'Strong outcome associations', 'Large reference datasets', 'Clinically interpretable native unit'],
    knownLimitations: ['Normative percentiles are population and protocol dependent', 'Wearable estimates are not direct VO₂max', 'No validated conversion to biological-age years', 'CPET access is limited'],
    validationHistory: ['FRIEND reference standards and equations', 'Large clinical cohort outcome associations'],
    currentResearchStatus: 'Strong fitness and outcome construct; no validated biological-age modifier or age conversion.',
    productionReadinessSummary: 'Promising as separately labeled normative context after protocol and reference governance; not ready as an age component.',
    expectedFutureStability: 'Moderate if direct CPET protocol and reference population are versioned.',
    importantAssumptions: ['Maximal effort and quality criteria are satisfied', 'Reference population and modality match', 'Direct and estimated measurements are never interchanged'],
    knownControversies: ['Fitness “age” labels often convert percentiles into years without validated meaning', 'Body-size normalization changes interpretation'],
    missingEvidence: ['Validated contribution to a multimodal biological-age construct', 'Protocol-independent harmonization', 'Product-accessible direct CPET integration'],
    populationLimitations: ['Reference standards vary by country, age, sex, body composition, and modality'],
    measurementBurden: 'high',
    costImplications: 'high',
    clinicalAvailability: 'specialty',
  },
  rubric: defineCandidateRubric(VO2MAX_EVIDENCE, {
    scientific_evidence_quality: ['strong', 'Direct cardiorespiratory fitness and normative evidence are substantial.'],
    external_validation: ['strong', 'Reference standards and outcome relationships have been studied across large cohorts.'],
    independent_replication: ['strong', 'The fitness-outcome relationship is repeatedly observed.'],
    population_diversity: ['moderate', 'Reference datasets include broad adults but remain population and protocol specific.'],
    clinical_relevance: ['strong', 'Direct CPET has established clinical and physiological meaning.'],
    longevity_relevance: ['strong', 'Cardiorespiratory fitness is strongly associated with health outcomes and longevity.'],
    construct_clarity: ['excellent', 'VO₂max has a clear native physiological unit; normative position is distinct from age.'],
    interpretability: ['strong', 'Direct measurement and reference percentile can be explained clearly.'],
    input_reliability: ['strong', 'Quality-controlled maximal CPET is reliable; estimates are not interchangeable.'],
    measurement_availability: ['limited', 'Direct CPET is not routinely available to most users.'],
    standardization: ['moderate', 'Protocol, modality, maximal effort, and reference selection must be controlled.'],
    implementation_complexity: ['moderate', 'Normative context is feasible but requires protocol and reference governance.'],
    maintenance_burden: ['moderate', 'Reference updates and protocol compatibility require surveillance.'],
    calibration_availability: ['moderate', 'FRIEND references exist but population and modality selection remain necessary.'],
    version_stability: ['moderate', 'A frozen reference version can be stable, though standards evolve.'],
    temporal_robustness: ['moderate', 'Point assessments are reproducible under protocol but can change with training or illness.'],
    generalizability: ['moderate', 'Normative interpretation depends on demographic and testing context.'],
    risk_of_misuse: ['limited', 'Fitness age or wearable substitutions could overstate the evidence.'],
    double_counting_risk: ['moderate', 'Physiology may correlate with cardiometabolic and functional components without sharing blood inputs.'],
    correlation_with_production_model: ['moderate', 'Likely related through health status but not trained directly on Clinical PhenoAge.'],
    architecture_compatibility: ['strong', 'A quality-controlled input policy and Normative Context role already exist.'],
    multimodal_suitability: ['limited', 'It may add independent context, but no validated numerical composite role exists.'],
    expert_review_need: ['moderate', 'Exercise-physiology and reference-population review are required.'],
    future_calibration_need: ['moderate', 'Reference selection and stratification require versioned governance.'],
    additional_governance_need: ['moderate', 'Direct-versus-estimated source enforcement and protocol surveillance are required.'],
  }),
  architectureFit: defineArchitectureFit({
    scientific_registry: ['compatible', 'Normative VO₂max and outcome literature are registered separately.'],
    eligibility_engine: ['compatible_with_conditions', 'The existing policy requires quality-controlled direct CPET and calibration.'],
    execution_authorization: ['blocked', 'No normative execution engine or authorized reference integration exists.'],
    versioning: ['compatible_with_conditions', 'A specific reference population and protocol version must be selected.'],
    scientific_governance: ['compatible_with_conditions', 'Component review can preserve normative-only use.'],
    component_contracts: ['compatible', 'It maps to Normative Context and cannot produce age in years.'],
    temporal_policies: ['compatible_with_conditions', 'Point-assessment freshness and cross-component alignment need model-specific policy.'],
    uncertainty_architecture: ['compatible', 'Protocol, effort, population, and temporal uncertainties can remain distinct.'],
    combination_safety: ['blocked', 'No validated numerical relationship to a biological-age composite exists.'],
    presentation_layer: ['compatible_with_conditions', 'Future presentation must use VO₂max and normative language, never fitness age.'],
    multimodal_framework: ['compatible_with_conditions', 'May coexist as context but cannot numerically alter age.'],
    living_sphere: ['not_applicable', 'Fitness domain visualization remains separate from scientific age evaluation.'],
  }),
  risks: defineCandidateRisks({
    scientific_uncertainty: ['moderate', 'Normative fitness is strong science; its relationship to biological age is unvalidated.', 'Keep the output in native and normative constructs.'],
    implementation_risk: ['moderate', 'Protocol or reference mismatch can invalidate interpretation.', 'Require exact CPET provenance and reference version.'],
    maintenance_risk: ['moderate', 'Reference standards and testing protocols evolve.', 'Version references and schedule evidence review.'],
    future_migration_risk: ['moderate', 'Changing normative datasets alters percentiles.', 'Never overwrite prior reference versions.'],
    regulatory_ambiguity: ['moderate', 'Clinical exercise results require bounded interpretation.', 'Use fitness context rather than diagnostic claims.'],
    clinical_interpretation_risk: ['moderate', 'Estimated and measured VO₂max may be conflated.', 'Reject unsupported device estimates.'],
    user_misunderstanding_risk: ['high', 'Users may interpret percentile-derived “fitness age” as biological age.', 'Prohibit age conversion and years labels.'],
    biological_age_overstatement_risk: ['high', 'Strong longevity associations do not validate age conversion.', 'Retain Normative Context role.'],
    unsupported_marketing_risk: ['high', 'Fitness age is commercially attractive but scientifically unsupported here.', 'Approve terminology and claims centrally.'],
    double_counting_risk: ['moderate', 'Fitness overlaps broader cardiorespiratory and functional evidence.', 'Preserve correlation metadata if future combination is reviewed.'],
    population_transportability_risk: ['moderate', 'Normative standards vary by population and modality.', 'Use only validated reference strata.'],
    version_drift_risk: ['moderate', 'Reference equations and definitions change.', 'Bind every output to an immutable reference version.'],
  }),
  implementationReadiness: 'scientifically_promising',
  readinessReasons: ['High-value independent physiological context.', 'No validated transformation into biological-age years or composite contribution.', 'Direct CPET availability is limited.'],
  priorityTier: 'tier_2',
  priorityRationale: ['Worth implementing after KDM calibration work as a separately labeled context component.', 'It strengthens interpretation without pretending to be another age model.'],
  recommendedAction: 'Keep VO₂max contextual; prepare a future direct-CPET normative component only after protocol and reference review.',
  governancePrerequisites: ['Select an exact direct CPET protocol', 'Select and license a reference version', 'Define maximal-effort and quality criteria', 'Prohibit wearable substitution and age conversion', 'Validate presentation terminology'],
  canBypassGovernance: false,
} as const satisfies ScientificCandidateDossier;

export const CLINICAL_CANDIDATE_DOSSIERS = [
  CLINICAL_PHENOAGE_REFERENCE_DOSSIER,
  KDM_CANDIDATE_DOSSIER,
  VO2MAX_CANDIDATE_DOSSIER,
] as const satisfies readonly ScientificCandidateDossier[];
