import { defineKdmArchitecture, defineKdmRubric } from './builders';
import {
  BIOAGE_V2_PANEL,
  CALERIE_2017_PANEL,
  CHAN_REDUCED_PANEL,
  LEVINE_KDM1_PANEL,
  LEVINE_KDM2_FEMALE_PANEL,
  LEVINE_KDM2_MALE_PANEL,
  LIU_CHNS_PANEL,
  MAK_18_PANEL,
  ZHONG_SLAS_FEMALE_PANEL,
  ZHONG_SLAS_MALE_PANEL,
} from './biomarkers';
import type {
  KdmBiomarkerDefinition,
  KdmCalibrationDossier,
  KdmPopulationProfile,
  KdmValidationProfile,
} from './contracts';

function uniquePanel(...panels: readonly (readonly KdmBiomarkerDefinition[])[]): readonly KdmBiomarkerDefinition[] {
  return [...new Map(panels.flat().map(item => [item.id, item])).values()];
}

function population(overrides: Partial<KdmPopulationProfile>): KdmPopulationProfile {
  return {
    country: 'Not applicable', sampleSize: 'Not applicable', ageRange: 'Not applicable',
    sexHandling: 'Not applicable', ethnicityAndDiversity: 'Not reported',
    healthSelection: 'Not applicable', referenceCohort: 'Not applicable',
    selectionBias: ['Not applicable'], geographicBias: 'Not applicable',
    transportability: 'No empirical transport claim is available.',
    internationalConsumerSuitability: 'not_applicable', ...overrides,
  };
}

function validation(overrides: Partial<KdmValidationProfile>): KdmValidationProfile {
  return {
    developmentValidation: [], independentReplications: [], externalValidations: [],
    outcomeCoverage: [], exactCalibrationReplicated: false,
    limitations: ['No exact-calibration validation was identified.'], ...overrides,
  };
}

const BLOCKED_ARCHITECTURE = defineKdmArchitecture(
  ['blocked', 'This record does not identify an executable, versioned calibration.'],
  { rubric: ['compatible', 'The qualitative review can retain the record as evidence context.'] },
);

const CONDITIONAL_ARCHITECTURE = defineKdmArchitecture(
  ['compatible_after_prerequisites', 'The existing boundary can support a named version after calibration-specific evidence and validation are approved.'],
  {
    authorization: ['blocked', 'No KDM execution may be authorized in this evidence-review phase.'],
    validation: ['blocked', 'Independent reference fixtures and numerical validation do not yet exist.'],
    combination_safety: ['blocked', 'Incremental value and overlap with Clinical PhenoAge are unresolved.'],
    temporal_policies: ['compatible_after_prerequisites', 'Repeat-measurement comparability needs a fixed assay and collection policy.'],
  },
);

const RESEARCH_ARCHITECTURE = defineKdmArchitecture(
  ['compatible_after_prerequisites', 'The architecture can represent this calibration, but its scientific scope is not production-ready.'],
  {
    authorization: ['blocked', 'Research evidence does not authorize production execution.'],
    validation: ['blocked', 'Exact independent production validation is incomplete.'],
    combination_safety: ['blocked', 'No combination with Clinical PhenoAge is scientifically authorized.'],
  },
);

const NON_CALIBRATION_RUBRIC = defineKdmRubric(
  ['not_applicable', 'This publication is not a deployable calibration.'],
  {
    evidence_quality: ['strong', 'The peer-reviewed publication is authoritative for its stated methodological or validation role.'],
    scientific_maturity: ['moderate', 'The work is scientifically established within its stated scope.'],
    scientific_platform_suitability: ['limited', 'It is useful evidence context but cannot be a production model identity.'],
  },
);

export const KDM_CALIBRATION_DOSSIERS = [
  {
    id: 'klemera_doubal_method_2006',
    officialName: 'Klemera–Doubal Method (2006 methodological framework)',
    proposedVersionName: null,
    recordKind: 'method_only',
    disposition: 'rejected_for_production',
    primaryEvidenceId: 'klemera_doubal_2006',
    supportingEvidenceIds: [],
    authors: 'Klemera P, Doubal S', publicationYear: 2006,
    purpose: 'Define and test a statistical method for estimating a latent age-equivalent construct.',
    population: population({
      sampleSize: 'Computer-generated simulations; no human reference cohort',
      referenceCohort: 'Simulated data',
      transportability: 'The method is portable; no human calibration is supplied.',
    }),
    biomarkerPanel: [],
    biomarkerPanelScope: 'No biomarker panel, clinical units, assay context, or human reference population is defined.',
    statisticalMethodology: 'A latent-age estimation framework evaluated with simulated data; it is not a fixed clinical model.',
    requiredPreprocessing: ['Calibration-specific preprocessing must be defined by a later empirical model.'],
    calibrationStrategy: 'No empirical human calibration.',
    versionStability: 'Stable as a method publication, unusable as a production calibration.',
    validation: validation({
      developmentValidation: ['Simulation experiments in the primary publication'],
      independentReplications: ['The method has been applied in many cohorts using different panels and reference samples.'],
      limitations: ['Method reuse does not validate any one future Vitalspan calibration.'],
    }),
    knownImplementations: ['Levine NHANES III', 'BioAge toolkit', 'Cohort-specific research adaptations'],
    currentScientificUse: 'General statistical framework for cohort-specific biological-age research.',
    knownLimitations: ['No fixed inputs', 'No human reference sample', 'No units', 'No single reproducible output definition'],
    clinicalRelevance: 'Methodological only.', longevityRelevance: 'Indirect; depends on the chosen calibration and validation outcomes.',
    interpretability: 'Cannot be interpreted without naming the calibration.',
    transportability: 'Method transport does not imply calibrated-output transport.',
    maintenanceBurden: 'Undefined until a calibration is selected.', scientificMaturity: 'strong',
    productionReadiness: 'rejected', architecture: BLOCKED_ARCHITECTURE, rubric: NON_CALIBRATION_RUBRIC,
    rejectionOrSelectionRationale: ['Generic KDM violates the named-calibration requirement.', 'Unknown is scientifically preferable to instantiating this method without a calibration.'],
  },
  {
    id: 'levine_nhanes_iii_kdm1_2013',
    officialName: 'Levine 2013 NHANES III KDM1 (10-biomarker, sex-stratified calibration)',
    proposedVersionName: 'KDM-Levine-NHANES-III-KDM1 v1.0.0',
    recordKind: 'named_calibration', disposition: 'selected_after_prerequisites',
    primaryEvidenceId: 'levine_kdm_2013',
    supportingEvidenceIds: ['belsky_dunedin_2015', 'hastings_nhanes_iv_2019', 'kwon_bioage_2021'],
    authors: 'Levine ME', publicationYear: 2013,
    purpose: 'Estimate age-equivalent physiology from a fixed multisystem panel calibrated in NHANES III.',
    population: population({
      country: 'United States', sampleSize: '9,389 complete-case participants', ageRange: '30–75 years',
      sexHandling: 'Calibration parameters estimated separately for men and women; the same ten biomarkers are required.',
      ethnicityAndDiversity: 'Nationally representative US survey with NHANES race and ethnicity groups; subgroup transport was not the calibration objective.',
      healthSelection: 'General noninstitutionalized population; complete-case analytic sample.',
      referenceCohort: 'NHANES III, collected 1988–1994',
      selectionBias: ['Only about 75% of age-eligible participants had complete biomarker data', 'Excluded participants were older and more likely to die during follow-up'],
      geographicBias: 'Historical United States calibration.',
      transportability: 'Plausible for research reuse but unproven as an international consumer-health calibration.',
      internationalConsumerSuitability: 'limited',
    }),
    biomarkerPanel: LEVINE_KDM1_PANEL,
    biomarkerPanelScope: 'Exact union: chronological age plus all ten biomarkers used by KDM1 for both sex strata.',
    statisticalMethodology: 'KDM applied to ten age-associated biomarkers; calibration and mortality comparisons were sex stratified.',
    requiredPreprocessing: ['Exact historical input identity and units', 'Sex-stratum selection', 'Complete-case input policy', 'Compatible spirometry and CMV assay context', 'No substituted or inferred biomarkers'],
    calibrationStrategy: 'Sex-specific calibration in the NHANES III complete-case population aged 30–75.',
    versionStability: 'A fixed published panel and widely referenced “Levine Original” implementation exist; historical assay artifacts still require independent freezing.',
    validation: validation({
      developmentValidation: ['18-year NHANES III mortality follow-up with 1,843 deaths', 'Head-to-head comparison with chronological age and other biological-age algorithms'],
      independentReplications: ['Applied as the published 10-biomarker age in the Dunedin cohort', 'Reproduced as “Levine Original” by BioAge'],
      externalValidations: ['NHANES IV healthspan and mortality comparisons', 'Dunedin age-38 physical, cognitive, retinal, self-rated-health, and facial-age associations'],
      outcomeCoverage: ['All-cause age-related mortality', 'Physical functioning', 'Disability', 'Self-rated health', 'Midlife physiological and functional correlates'],
      exactCalibrationReplicated: true,
      limitations: ['Many later studies omit CMV optical density or alter the panel and therefore are not exact replications', 'No direct international prospective product validation'],
    }),
    knownImplementations: ['Levine 2013 KDM1', 'BioAge “Levine Original”', 'Dunedin cross-sectional Biological Age reuse'],
    currentScientificUse: 'Historical reference calibration and comparator in biological-age research.',
    knownLimitations: ['Historical assays', 'CMV optical density is not routinely harmonized', 'Spirometry protocol dependence', 'Binary sex-specific calibration', 'Cross-sectional construct', 'International transport not established'],
    clinicalRelevance: 'Inputs span inflammation, renal, metabolic, hepatic, pulmonary, cardiovascular, and immune evidence; the result is not diagnostic.',
    longevityRelevance: 'Direct mortality-prediction evidence and later healthspan associations.',
    interpretability: 'High only when the exact panel, sex stratum, reference cohort, and limitations remain visible.',
    transportability: 'Requires prospective population and laboratory compatibility validation before international use.',
    maintenanceBurden: 'Moderate to high because CMV assay and spirometry protocols must be governed.', scientificMaturity: 'strong',
    productionReadiness: 'proceed_after_prerequisites', architecture: CONDITIONAL_ARCHITECTURE,
    rubric: defineKdmRubric(['moderate', 'Evidence is useful but calibration-specific limitations remain.'], {
      evidence_quality: ['strong', 'The calibration and mortality comparison are peer reviewed and transparent.'],
      replication: ['strong', 'The exact ten-biomarker reference has been reused and reproduced in peer-reviewed work.'],
      external_validation: ['moderate', 'External outcomes exist, but international prospective product validation does not.'],
      longevity_relevance: ['strong', 'The calibration has long-follow-up mortality evidence.'],
      construct_clarity: ['strong', 'The same ten inputs and sex-specific calibration identity can be frozen unambiguously.'],
      version_stability: ['strong', 'Later literature recognizes the ten-biomarker model as “Levine Original.”'],
      biomarker_quality: ['moderate', 'The panel is multisystem, but CMV optical density and FEV1 are protocol sensitive.'],
      generalizability: ['limited', 'A historical US reference cannot be assumed to transport internationally.'],
      double_counting_risk: ['limited', 'Four exact blood inputs overlap Clinical PhenoAge, with additional related glycemic evidence.'],
      clinical_phenoage_compatibility: ['limited', 'It may add pulmonary, pressure, immune, and renal evidence, but incremental independence is not yet demonstrated.'],
      consumer_health_suitability: ['limited', 'The panel is understandable but not routinely complete in consumer records.'],
      scientific_platform_suitability: ['strong', 'It is named, versionable, auditable, and compatible with fail-closed execution architecture.'],
    }),
    rejectionOrSelectionRationale: ['Most mature fixed KDM identity reviewed', 'Same panel across sex strata improves version clarity', 'More peer-reviewed reuse than newer cohort-specific calibrations', 'Lower overlap with Clinical PhenoAge than BioAge V2', 'Selection is conditional and does not authorize implementation'],
  },
  {
    id: 'levine_nhanes_iii_kdm2_2013',
    officialName: 'Levine 2013 NHANES III KDM2 (PCA-selected sex-specific seven-biomarker calibrations)',
    proposedVersionName: null, recordKind: 'named_calibration', disposition: 'research_only',
    primaryEvidenceId: 'levine_kdm_2013', supportingEvidenceIds: [], authors: 'Levine ME', publicationYear: 2013,
    purpose: 'Use sex-specific reduced panels selected from the ten KDM1 inputs.',
    population: population({
      country: 'United States', sampleSize: '9,389 complete-case participants', ageRange: '30–75 years',
      sexHandling: 'Different seven-biomarker panels for men and women.',
      ethnicityAndDiversity: 'Nationally representative US survey; no calibration by ethnicity.',
      healthSelection: 'General population complete cases.', referenceCohort: 'NHANES III, 1988–1994',
      selectionBias: ['Complete-case selection', 'Panel selected within the same dataset used for outcome comparison'],
      geographicBias: 'Historical United States calibration.',
      transportability: 'Sex-specific input identity and older assays materially limit transport.', internationalConsumerSuitability: 'limited',
    }),
    biomarkerPanel: uniquePanel(LEVINE_KDM2_MALE_PANEL, LEVINE_KDM2_FEMALE_PANEL),
    biomarkerPanelScope: 'Union of two different seven-biomarker panels; sex-specific membership is documented separately and must never be merged.',
    statisticalMethodology: 'KDM using reduced, sex-specific panels selected through principal-component analysis.',
    requiredPreprocessing: ['Exact sex-specific panel selection', 'Historical units', 'Compatible CMV and spirometry protocols', 'No cross-sex panel substitution'],
    calibrationStrategy: 'Separate male and female reduced-panel calibrations in NHANES III.',
    versionStability: 'Clearly published, but later literature more often operationalizes the ten-biomarker “Levine Original.”',
    validation: validation({
      developmentValidation: ['Best mortality discrimination among algorithms compared in the 2013 NHANES III paper'],
      outcomeCoverage: ['Age-related mortality'],
      limitations: ['Predominantly internal comparison', 'Limited exact-panel external replication', 'Different biomarker identity by sex'],
    }),
    knownImplementations: ['Levine 2013 KDM2'], currentScientificUse: 'Historical methodological comparator.',
    knownLimitations: ['Different male and female input panels', 'No policy for people outside the historical binary stratification', 'CMV and spirometry burden', 'Limited exact replication'],
    clinicalRelevance: 'Multisystem but panel content changes by sex.', longevityRelevance: 'Strong internal mortality association.',
    interpretability: 'Reduced by sex-dependent input identity.', transportability: 'Limited without new validation that would itself create a new version.',
    maintenanceBurden: 'High due to two panels and two assay-governance paths.', scientificMaturity: 'moderate',
    productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['limited', 'The exact reduced calibration has limited external production evidence.'], {
      evidence_quality: ['strong', 'The primary comparison is peer reviewed.'], longevity_relevance: ['strong', 'It performed best for mortality within the source study.'],
      construct_clarity: ['moderate', 'Two sex-specific input sets must be treated as separate calibration branches.'],
      version_stability: ['limited', 'Later canonical reuse centers on the ten-biomarker version.'],
      consumer_health_suitability: ['limited', 'Sex-dependent panel requirements complicate fair product eligibility.'],
    }),
    rejectionOrSelectionRationale: ['Not selected because exact external reuse is thinner than KDM1', 'Different input panels by sex impair longitudinal and governance simplicity', 'Internal performance advantage does not establish international production readiness'],
  },
  {
    id: 'belsky_dunedin_reuse_2015', officialName: 'Dunedin reuse of the published 10-biomarker NHANES KDM age',
    proposedVersionName: null, recordKind: 'external_reuse', disposition: 'not_a_distinct_calibration',
    primaryEvidenceId: 'belsky_dunedin_2015', supportingEvidenceIds: ['levine_kdm_2013'],
    authors: 'Belsky DW, Caspi A, Houts R, et al.', publicationYear: 2015,
    purpose: 'Test the published NHANES-derived KDM age in a same-age young-adult cohort.',
    population: population({ country: 'New Zealand', sampleSize: '954 longitudinal participants from a 1,037-member birth cohort', ageRange: 'KDM assessed at age 38', sexHandling: 'Both sexes; no new calibration stratification', ethnicityAndDiversity: 'Single 1972–1973 Dunedin birth cohort', healthSelection: 'Largely free of age-related disease at age 38', referenceCohort: 'Retained the published NHANES reference', selectionBias: ['Single birth cohort', 'Single city and country'], geographicBias: 'Dunedin, New Zealand', transportability: 'Supports external construct relevance, not a new calibration.', internationalConsumerSuitability: 'not_applicable' }),
    biomarkerPanel: LEVINE_KDM1_PANEL, biomarkerPanelScope: 'Reused the published ten-biomarker NHANES panel; no new KDM panel was calibrated.',
    statisticalMethodology: 'External application of the published KDM age alongside a separate longitudinal Pace of Aging measure.',
    requiredPreprocessing: ['Compatibility with the published NHANES inputs'], calibrationStrategy: 'No new KDM calibration.',
    versionStability: 'Evidence for Levine KDM1, not an independent version.',
    validation: validation({ developmentValidation: ['Not applicable'], externalValidations: ['Association with 12-year physiological change and age-38 physical, cognitive, retinal, perceived-health, and facial-age measures'], outcomeCoverage: ['Midlife function', 'Longitudinal physiological change'], exactCalibrationReplicated: true, limitations: ['All participants shared the same chronological age', 'Single birth cohort'] }),
    knownImplementations: ['Dunedin Study age-38 analysis'], currentScientificUse: 'External validation evidence for the published NHANES calibration.',
    knownLimitations: ['Not a new calibration', 'Same-age cohort cannot validate behavior across the adult age range'], clinicalRelevance: 'Supports midlife construct validity.', longevityRelevance: 'Indirect; no mortality calibration was developed here.', interpretability: 'Clear as external reuse.', transportability: 'Useful but insufficient for product transport.', maintenanceBurden: 'None beyond the parent calibration.', scientificMaturity: 'moderate', productionReadiness: 'not_recommended', architecture: BLOCKED_ARCHITECTURE, rubric: NON_CALIBRATION_RUBRIC, rejectionOrSelectionRationale: ['Must be counted as validation of Levine KDM1, not as a competing calibration.'],
  },
  {
    id: 'calerie_nhanes_adaptation_2017', officialName: 'CALERIE NHANES-derived 10-biomarker KDM adaptation (2017)',
    proposedVersionName: null, recordKind: 'study_specific_adaptation', disposition: 'research_only',
    primaryEvidenceId: 'belsky_calerie_2017', supportingEvidenceIds: ['levine_kdm_2013'], authors: 'Belsky DW, Huffman KM, Pieper CF, Shalev I, Kraus WE', publicationYear: 2017,
    purpose: 'Evaluate longitudinal change during a two-year caloric-restriction trial.',
    population: population({ country: 'United States', sampleSize: '220 randomized participants; 611 possible visit records', ageRange: 'Young and middle-aged adults; mean baseline age 38', sexHandling: 'Sex-specific reference distributions where specified', ethnicityAndDiversity: 'Approximately 95% White', healthSelection: 'Healthy, non-obese trial volunteers', referenceCohort: 'NHANES data used to derive the study panel', selectionBias: ['Trial volunteer selection', 'Healthy non-obese eligibility', 'Limited racial diversity'], geographicBias: 'United States trial sites and US reference data', transportability: 'Intervention sensitivity does not establish consumer population transport.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: CALERIE_2017_PANEL, biomarkerPanelScope: 'Exact study panel; glycated hemoglobin was estimated from serum glucose in the trial rather than directly measured.',
    statisticalMethodology: 'NHANES-derived KDM adapted to the safety-laboratory measures available in CALERIE.',
    requiredPreprocessing: ['Study-specific transformations', 'Trial used an inferred glycated-hemoglobin value', 'Longitudinal visit alignment', 'Study-specific missing-value handling'],
    calibrationStrategy: 'Adapt panel availability to the CALERIE trial and apply NHANES-derived parameters.',
    versionStability: 'Superseded for later BioAge demonstration by a different V2 panel and reference-period choice.',
    validation: validation({ developmentValidation: ['Independent NHANES checks for age, function, and social patterning'], externalValidations: ['CALERIE randomized longitudinal response'], outcomeCoverage: ['Two-year within-person change', 'Physical limitation and social patterning in NHANES'], limitations: ['Small, selected trial', 'Input inference and missing-value imputation are incompatible with Vitalspan safeguards', 'Intervention-response interpretation remains unsettled'] }),
    knownImplementations: ['CALERIE 2017 Biobank analysis'], currentScientificUse: 'Research outcome in geroscience intervention analysis.',
    knownLimitations: ['Inferred input', 'Imputed missing visits', 'Highly selected trial', 'Reference-period sensitivity'], clinicalRelevance: 'Routine panel but used under study-specific assumptions.', longevityRelevance: 'Suggestive intervention sensitivity, not proof of lifespan or treatment effectiveness.', interpretability: 'Compromised by inferred input and trial-specific preprocessing.', transportability: 'Low.', maintenanceBurden: 'High if reproduced faithfully.', scientificMaturity: 'limited', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['limited', 'The adaptation is valuable research but too study-specific for production.'], {
      evidence_quality: ['moderate', 'Randomized longitudinal evidence is notable but the calibration itself is adapted.'],
      longevity_relevance: ['moderate', 'Longitudinal intervention sensitivity is relevant but does not prove lifespan or treatment-effect validity.'],
      consumer_health_suitability: ['insufficient', 'Inferred and imputed study inputs conflict with fail-closed consumer-health evidence handling.'],
    }),
    rejectionOrSelectionRationale: ['Not selected because inferred and imputed inputs conflict with fail-closed policy', 'Trial-specific calibration choices lack stable general-population meaning'],
  },
  {
    id: 'bioage_v2_nhanes_iii_2021', officialName: 'BioAge V2 NHANES III KDM calibration for CALERIE', proposedVersionName: null,
    recordKind: 'study_specific_adaptation', disposition: 'research_only', primaryEvidenceId: 'kwon_bioage_2021', supportingEvidenceIds: ['belsky_calerie_2017', 'hastings_nhanes_iv_2019'], authors: 'Kwon D, Belsky DW', publicationYear: 2021,
    purpose: 'Demonstrate a customizable toolkit using a combined 12-biomarker panel and CALERIE data.',
    population: population({ country: 'United States', sampleSize: 'NHANES III training; NHANES IV testing; 207 CALERIE baseline participants', ageRange: 'NHANES III reference ages 30–75; CALERIE midlife adults', sexHandling: 'NHANES parameters estimated separately for men and women', ethnicityAndDiversity: 'NHANES test analyses included sex and race strata; CALERIE was selected and predominantly White', healthSelection: 'NHANES general population; CALERIE healthy non-obese volunteers', referenceCohort: 'NHANES III nonpregnant complete cases aged 30–75', selectionBias: ['Complete-case training', 'CALERIE volunteer and trial selection'], geographicBias: 'United States', transportability: 'Toolkit portability does not establish V2 calibration transport.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: BIOAGE_V2_PANEL, biomarkerPanelScope: 'Exact V2 panel: chronological age plus twelve clinical biomarkers.',
    statisticalMethodology: 'KDM parametrized in NHANES III, compared in NHANES IV, then projected into CALERIE.',
    requiredPreprocessing: ['Sex-specific outlier handling', 'Published skew transformations', 'NHANES assay-period harmonization', 'Complete compatible panel'], calibrationStrategy: 'Train the chosen V2 panel in NHANES III; test in NHANES IV.',
    versionStability: 'Panel is published, but BioAge is intentionally a customization framework rather than one immutable model family.',
    validation: validation({ developmentValidation: ['NHANES IV mortality, health, functioning, and socioeconomic comparisons'], externalValidations: ['CALERIE repeated-measure intervention analysis'], outcomeCoverage: ['Mortality', 'Function', 'Self-rated health', 'Socioeconomic patterning', 'Longitudinal trial change'], limitations: ['No independent implementation validation', 'High overlap with Clinical PhenoAge', 'CALERIE remains a selected trial'] }),
    knownImplementations: ['BioAge R package V2 demonstration'], currentScientificUse: 'Research toolkit example and trial analysis.',
    knownLimitations: ['Eight exact blood measurements overlap Clinical PhenoAge', 'Toolkit allows arbitrary new panels', 'Assay harmonization burden', 'Limited independent replication of exact V2'], clinicalRelevance: 'Routine blood panel.', longevityRelevance: 'Mortality and healthspan associations plus trial sensitivity.', interpretability: 'Good at input level; poor as an independent modality beside Clinical PhenoAge.', transportability: 'Requires new validation.', maintenanceBurden: 'High due to historical NHANES harmonization and panel drift risk.', scientificMaturity: 'moderate', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['moderate', 'The published pipeline is useful but remains research-oriented.'], { version_stability: ['limited', 'Customization is a feature of the toolkit and a liability for immutable production identity.'], double_counting_risk: ['insufficient', 'Eight exact inputs overlap Clinical PhenoAge.'], clinical_phenoage_compatibility: ['insufficient', 'The panel is largely a recombination of the production blood model inputs.'], consumer_health_suitability: ['moderate', 'Inputs are mostly routine, but scientific independence is weak.'] }),
    rejectionOrSelectionRationale: ['Not selected because double-counting risk with Clinical PhenoAge is highest', 'BioAge software is not itself a calibration identity', 'Exact V2 independent replication is limited'],
  },
  {
    id: 'zhong_slas_kdm_2020', officialName: 'Zhong Singapore Longitudinal Aging Study sex-specific KDM calibration', proposedVersionName: null,
    recordKind: 'named_calibration', disposition: 'research_only', primaryEvidenceId: 'zhong_slas_kdm_2020', supportingEvidenceIds: [], authors: 'Zhong X, Lu Y, Gao Q, et al.', publicationYear: 2020,
    purpose: 'Estimate physiological age in older Chinese Singaporeans using sex-specific functional and clinical panels.',
    population: population({ country: 'Singapore', sampleSize: '2,844 Chinese Singaporeans', ageRange: '55–94 years, evaluated in 55–70 and 71–94 subgroups', sexHandling: 'Separate stepwise-selected panels for males and females', ethnicityAndDiversity: 'Chinese Singaporean older-adult cohort', healthSelection: 'Community-dwelling longitudinal aging cohort', referenceCohort: 'Singapore Longitudinal Aging Study 2', selectionBias: ['Older-adult-only cohort', 'Single ethnic and national context', 'Data-driven selection in the development cohort'], geographicBias: 'Singapore Chinese population', transportability: 'Unknown for younger adults, non-Chinese populations, and different functional-test protocols.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: uniquePanel(ZHONG_SLAS_MALE_PANEL, ZHONG_SLAS_FEMALE_PANEL),
    biomarkerPanelScope: 'Published sex-specific reduced panels include eight male and ten female markers. Accessible summaries differ on one functional or hematologic label; authoritative full-text artifact resolution is a prerequisite, and this union is not executable.',
    statisticalMethodology: 'KDM compared with regression, principal-component, and machine-learning approaches after sex-specific stepwise biomarker selection.',
    requiredPreprocessing: ['Exact sex-specific panel resolution', 'Standardized functional and cognitive test protocols', 'Renal-function definition', 'No panel substitution'],
    calibrationStrategy: 'Sex-specific calibration in an older Chinese Singaporean cohort.',
    versionStability: 'Peer-reviewed identity exists, but exact production artifacts and panel transcription require author-level audit.',
    validation: validation({ developmentValidation: ['Eight-year frailty and mortality follow-up', 'Comparison with chronological age and other estimation methods'], outcomeCoverage: ['Mortality', 'Frailty', 'Health and functional characteristics'], limitations: ['No independent external cohort', 'Development and validation use the same cohort resource', 'Restricted age and ethnicity'] }),
    knownImplementations: ['Singapore Longitudinal Aging Study KDM'], currentScientificUse: 'Older-adult Asian cohort research.',
    knownLimitations: ['Older age range', 'Sex-specific panel identity', 'Functional-test and cognitive-test burden', 'No independent replication', 'Restricted population'], clinicalRelevance: 'Strong functional relevance but not a routine laboratory model.', longevityRelevance: 'Eight-year mortality and frailty prediction.', interpretability: 'Inputs are understandable but protocol dependent.', transportability: 'Low outside the source population.', maintenanceBurden: 'High because functional and cognitive protocols must be reproduced.', scientificMaturity: 'moderate', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['limited', 'The cohort-specific evidence does not support international production.'], { longevity_relevance: ['strong', 'Mortality and frailty were prospectively assessed.'], biomarker_quality: ['moderate', 'Functional and clinical inputs span multiple systems but are protocol sensitive.'], population_robustness: ['limited', 'One older Chinese Singaporean cohort anchors the calibration.'], version_stability: ['limited', 'Exact panel artifacts require authoritative resolution.'], consumer_health_suitability: ['insufficient', 'Functional and cognitive testing cannot be assumed equivalent across product contexts.'] }),
    rejectionOrSelectionRationale: ['Not selected because the age range begins at 55', 'No independent external validation', 'High functional-test protocol burden', 'Sex-specific panel artifacts require further resolution'],
  },
  {
    id: 'liu_chns_kdm_2020', officialName: 'Liu CHNS 12-biomarker Chinese KDM-BA calibration', proposedVersionName: null,
    recordKind: 'named_calibration', disposition: 'research_only', primaryEvidenceId: 'liu_china_kdm_2020', supportingEvidenceIds: [], authors: 'Liu Z, Kuo PL, Zhou Y, et al.', publicationYear: 2020,
    purpose: 'Develop and validate a Chinese-population KDM age from routine clinical measurements.',
    population: population({ country: 'China', sampleSize: '8,119 CHNS development participants; 9,304 CHARLS replication participants', ageRange: 'CHNS 20–79; CHARLS 45–99', sexHandling: 'Gender adjusted in outcomes; one published panel rather than different sex-specific panels', ethnicityAndDiversity: 'Mainland Chinese nationwide cohorts across multiple provinces', healthSelection: 'Community population with healthy-subgroup analyses', referenceCohort: 'CHNS 2009 wave', selectionBias: ['Complete biomarker cases', 'CHARLS lacked four development biomarkers', 'Mortality ascertainment limitations'], geographicBias: 'Mainland China', transportability: 'Strong relevance within Chinese cohorts; external non-Chinese transport is unknown.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: LIU_CHNS_PANEL, biomarkerPanelScope: 'Exact 12-biomarker CHNS panel plus age; CHARLS replicated only an eight-biomarker adaptation and therefore did not exactly replicate the calibration.',
    statisticalMethodology: 'KDM developed from biomarkers selected for availability, aging relevance, low redundancy, and age association.',
    requiredPreprocessing: ['Published transformation of non-normal biomarkers', 'Complete panel', 'CHNS-compatible measurement definitions'], calibrationStrategy: 'Population-specific calibration in a nationwide Chinese cohort.',
    versionStability: 'Named and documented, but the external cohort used a reduced panel.',
    validation: validation({ developmentValidation: ['CHNS mortality and disease-count associations'], externalValidations: ['CHARLS mortality and disease-count replication using eight available biomarkers'], outcomeCoverage: ['Mortality', 'Cross-sectional and longitudinal disease counts'], limitations: ['The full 12-biomarker calibration was not exactly replicated in CHARLS', 'Mortality and disease timing limitations'] }),
    knownImplementations: ['CHNS 12-biomarker KDM-BA', 'CHARLS eight-biomarker adaptation'], currentScientificUse: 'Chinese population-aging research.',
    knownLimitations: ['Population-specific', 'Exact full-panel external replication absent', 'Ferritin and transferrin add context and assay burden', 'Outcome ascertainment limitations'], clinicalRelevance: 'Routine or broadly available clinical inputs.', longevityRelevance: 'Mortality association in Chinese cohorts.', interpretability: 'Good within the source population.', transportability: 'Not established outside China.', maintenanceBurden: 'Moderate.', scientificMaturity: 'moderate', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['moderate', 'Good population-specific evidence does not establish international transport.'], { population_robustness: ['strong', 'Two large nationwide Chinese cohorts were studied.'], external_validation: ['limited', 'The replication cohort used only eight of twelve biomarkers.'], generalizability: ['limited', 'Evidence is geographically specific.'], consumer_health_suitability: ['moderate', 'The panel is clinically accessible but not internationally validated.'] }),
    rejectionOrSelectionRationale: ['Not selected for an international product because external non-Chinese transport is unknown', 'The full panel lacks an exact independent replication', 'Country-specific automatic selection is prohibited'],
  },
  {
    id: 'chan_uk_biobank_kdm_2021', officialName: 'Chan UK Biobank 72-biomarker principal-component KDM age', proposedVersionName: null,
    recordKind: 'named_calibration', disposition: 'research_only', primaryEvidenceId: 'chan_ukb_kdm_2021', supportingEvidenceIds: [], authors: 'Chan MS, Arnold M, Offer A, et al.', publicationYear: 2021,
    purpose: 'Construct a broad multisystem biomarker age in healthy UK Biobank participants.',
    population: population({ country: 'United Kingdom', sampleSize: '141,254 healthy reference participants from 480,019 eligible UK Biobank participants', ageRange: '40–70 at recruitment', sexHandling: 'Separate male and female models; some important inputs differ by sex', ethnicityAndDiversity: 'UK Biobank volunteer cohort with limited representativeness and predominantly White participants', healthSelection: 'Highly selected healthy subset without chronic medication or major prior disease', referenceCohort: 'Healthy UK Biobank baseline subset, 2006–2010', selectionBias: ['Healthy-volunteer bias', '29.4% met healthy-subset definition', 'UK Biobank is not population representative'], geographicBias: 'United Kingdom', transportability: 'Limited by healthy selection, age range, sex-specific structure, and UK-specific measurement protocols.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: CHAN_REDUCED_PANEL, biomarkerPanelScope: 'The primary model used 72 quality-controlled biomarkers represented by 51 principal components. The structured list here is the published reduced-panel core only and is not an executable substitute.',
    statisticalMethodology: 'Sex-specific KDM over orthogonal principal components derived from 72 baseline physical and biochemical biomarkers; chronological age was not included as an input.',
    requiredPreprocessing: ['UK Biobank quality control', 'Height normalization for specified physical measures', 'Sex-specific principal-component transformation', 'Fixed component loadings', 'Exact full-panel availability'], calibrationStrategy: 'Healthy-subset, sex-specific UK Biobank calibration with principal-component decorrelation.',
    versionStability: 'Exact only while the 72-input preprocessing and component transform remain frozen.',
    validation: validation({ developmentValidation: ['Prospective chronic-disease mortality and age-related hospital admission within UK Biobank'], outcomeCoverage: ['Chronic-disease mortality', 'Age-related hospital admissions'], limitations: ['No independent external cohort validation of the exact transform', 'Development and outcome validation share one cohort resource', 'Reduced panel is a sensitivity model, not the full model'] }),
    knownImplementations: ['Chan et al. UK Biobank full and reduced-panel research models'], currentScientificUse: 'High-dimensional UK Biobank aging research.',
    knownLimitations: ['72-input burden', 'Complex preprocessing', 'Sex-specific component structure', 'Healthy-volunteer selection', 'No independent exact replication'], clinicalRelevance: 'Multisystem but not routine clinical workflow.', longevityRelevance: 'Prospective mortality and hospitalization associations.', interpretability: 'Lower because principal components mediate input contributions.', transportability: 'Low outside UK Biobank-compatible measurement pipelines.', maintenanceBurden: 'Very high.', scientificMaturity: 'moderate', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['limited', 'Large prospective evidence is offset by high-dimensional cohort specificity.'], { evidence_quality: ['strong', 'Large prospective outcome study.'], biomarker_quality: ['strong', 'Broad multisystem coverage.'], interpretability: ['limited', 'Principal components obscure direct input attribution.'], implementation_complexity: ['insufficient', 'Seventy-two inputs and a fixed sex-specific transform are impractical for consumer production.'], maintenance_burden: ['insufficient', 'Measurement and transform drift would be costly to govern.'], consumer_health_suitability: ['insufficient', 'The panel is not routinely obtainable.'] }),
    rejectionOrSelectionRationale: ['Not selected because it is impractical for routine international measurements', 'No independent exact external validation', 'Healthy UK volunteer calibration has limited transportability'],
  },
  {
    id: 'mak_nhanes_iii_18_kdm_2023', officialName: 'Mak NHANES III 18-biomarker KDM projected to UK Biobank', proposedVersionName: null,
    recordKind: 'named_calibration', disposition: 'research_only', primaryEvidenceId: 'mak_ukb_kdm_2023', supportingEvidenceIds: ['kwon_bioage_2021'], authors: 'Mak JKL, McMurran CE, Kuja-Halkola R, et al.', publicationYear: 2023,
    purpose: 'Create a cross-cohort compatible clinical-biomarker KDM for cancer-incidence research.',
    population: population({ country: 'United States training; United Kingdom projection', sampleSize: '7,694 NHANES III KDM reference participants; 3,849 NHANES IV test participants; 308,156 UK Biobank analysis participants', ageRange: 'NHANES III reference 30–75; UK Biobank 37–73', sexHandling: 'BioAge reference parameters are sex specific; UK outcomes were adjusted and stratified by sex', ethnicityAndDiversity: 'US reference and UK projection; UK Biobank remains predominantly White and selected', healthSelection: 'NHANES complete cases; UK participants with complete 18-biomarker data and no prior cancer', referenceCohort: 'NHANES III nonpregnant complete cases aged 30–75', selectionBias: ['Complete-case training and projection', 'UK Biobank healthy-volunteer bias', 'Cancer-free baseline selection'], geographicBias: 'US-to-UK calibration transfer', transportability: 'Some cross-country evidence, but only one exact-panel program and no international consumer validation.', internationalConsumerSuitability: 'limited' }),
    biomarkerPanel: MAK_18_PANEL, biomarkerPanelScope: 'Exact 18-biomarker panel plus chronological age; pulse was excluded because of high correlation with systolic pressure.',
    statisticalMethodology: 'A KDM instance created with BioAge, trained in NHANES III, tested in NHANES IV, and projected to UK Biobank.',
    requiredPreprocessing: ['Age-correlation and missingness screen', 'Exact cross-cohort unit harmonization', 'Complete panel', 'Sex-specific reference handling', 'Protocol-compatible spirometry and physical measurements'], calibrationStrategy: 'Cross-dataset panel chosen for availability in NHANES III and UK Biobank.',
    versionStability: 'Panel is explicit, but it is a recent study-specific program with few exact replications.',
    validation: validation({ developmentValidation: ['Mortality association in independent NHANES IV test data'], externalValidations: ['Prospective UK Biobank cancer-incidence analysis'], outcomeCoverage: ['Mortality', 'Any cancer and five site-specific cancers'], limitations: ['Only one research group has published the exact calibration', 'Unexpected inverse prostate-cancer association was sensitive to glycemic inputs', 'Cancer association is not general aging validation'] }),
    knownImplementations: ['Mak et al. 18-biomarker KDM'], currentScientificUse: 'UK Biobank cancer and later neurological-outcome research.',
    knownLimitations: ['Large panel', 'FEV1 and waist-protocol dependence', 'Recent exact calibration', 'Cancer-specific interpretation issues', 'Substantial Clinical PhenoAge overlap'], clinicalRelevance: 'Broadly clinical but high burden.', longevityRelevance: 'NHANES mortality test supports relevance; UK outcome focus is cancer.', interpretability: 'Good per input, complex as a whole.', transportability: 'More evidence than a single-cohort calibration but insufficient for production.', maintenanceBurden: 'High.', scientificMaturity: 'moderate', productionReadiness: 'research_only', architecture: RESEARCH_ARCHITECTURE,
    rubric: defineKdmRubric(['moderate', 'Cross-cohort design is promising but exact-calibration maturity is limited.'], { external_validation: ['strong', 'The training, NHANES test, and UK projection datasets are separated.'], replication: ['limited', 'Independent exact-panel replication is not established.'], biomarker_quality: ['moderate', 'Broad coverage includes protocol-sensitive physical measures.'], double_counting_risk: ['limited', 'Many exact inputs overlap Clinical PhenoAge.'], consumer_health_suitability: ['limited', 'Eighteen biomarkers plus spirometry and anthropometry create high evidence burden.'] }),
    rejectionOrSelectionRationale: ['Not selected because the exact calibration is recent and not independently replicated', 'Higher panel burden and Clinical PhenoAge overlap than Levine KDM1', 'Outcome-specific anomalies require further study'],
  },
  {
    id: 'nhanes_iv_validation_role', officialName: 'NHANES IV validation and custom-retraining role', proposedVersionName: null,
    recordKind: 'validation_dataset_role', disposition: 'not_a_distinct_calibration', primaryEvidenceId: 'hastings_nhanes_iv_2019', supportingEvidenceIds: ['kwon_bioage_2021'], authors: 'Hastings WJ, Shalev I, Belsky DW; Kwon D, Belsky DW', publicationYear: 2019,
    purpose: 'Validate NHANES III-trained models and support research customization; not define one canonical later calibration.',
    population: population({ country: 'United States', sampleSize: 'Varies by NHANES IV cycle and complete panel', ageRange: 'Adult NHANES cycle dependent', sexHandling: 'Sex-stratified standardization and analyses where specified', ethnicityAndDiversity: 'Nationally representative US survey cycles', healthSelection: 'General noninstitutionalized population', referenceCohort: 'NHANES IV is usually the test set in the reviewed BioAge program', selectionBias: ['Cycle-specific assay availability', 'Complete-panel selection'], geographicBias: 'United States', transportability: 'Valuable test evidence, not a production calibration.', internationalConsumerSuitability: 'not_applicable' }),
    biomarkerPanel: [], biomarkerPanelScope: 'No single canonical “NHANES IV KDM” panel was identified; panels vary by study and customization.',
    statisticalMethodology: 'External testing of NHANES III-derived KDM measures and custom research retraining.', requiredPreprocessing: ['Cycle-specific assay harmonization'], calibrationStrategy: 'No single reviewed calibration strategy.',
    versionStability: '“NHANES IV KDM” is ambiguous without study, cycles, panel, transformations, and reference definition.',
    validation: validation({ externalValidations: ['Mortality, health, functioning, and socioeconomic association testing for published and customized KDM measures'], outcomeCoverage: ['Mortality', 'Function', 'Disability', 'Self-rated health'], limitations: ['Validation-set use must not be mislabeled as a calibration'] }),
    knownImplementations: ['NHANES 1999–2002 comparison', 'BioAge NHANES IV test workflow'], currentScientificUse: 'External validation and methods comparison.',
    knownLimitations: ['Assay changes across cycles', 'No single fixed panel', 'No canonical version identity'], clinicalRelevance: 'Supports validation only.', longevityRelevance: 'Mortality outcome evidence.', interpretability: 'Clear only when identified as a test dataset.', transportability: 'Not applicable.', maintenanceBurden: 'Cycle harmonization is high.', scientificMaturity: 'strong', productionReadiness: 'not_recommended', architecture: BLOCKED_ARCHITECTURE, rubric: NON_CALIBRATION_RUBRIC,
    rejectionOrSelectionRationale: ['No canonical peer-reviewed NHANES IV calibration was identified', 'A dataset generation label is not a model version'],
  },
] as const satisfies readonly KdmCalibrationDossier[];

export function getKdmCalibrationDossier(id: string): KdmCalibrationDossier | undefined {
  return KDM_CALIBRATION_DOSSIERS.find(dossier => dossier.id === id);
}
