import type { KdmEvidenceReference } from './contracts';

export const KDM_CALIBRATION_EVIDENCE = [
  {
    id: 'klemera_doubal_2006',
    title: 'A new approach to the concept and computation of biological age',
    authors: 'Klemera P, Doubal S',
    journal: 'Mechanisms of Ageing and Development',
    year: 2006,
    doi: '10.1016/j.mad.2005.10.004',
    pmid: '16318865',
    pmcid: null,
    url: 'https://pubmed.ncbi.nlm.nih.gov/16318865/',
    role: 'method',
  },
  {
    id: 'levine_kdm_2013',
    title: 'Modeling the rate of senescence: can estimated biological age predict mortality more accurately than chronological age?',
    authors: 'Levine ME',
    journal: 'The Journals of Gerontology: Series A',
    year: 2013,
    doi: '10.1093/gerona/gls233',
    pmid: '23213031',
    pmcid: 'PMC3660119',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3660119/',
    role: 'development',
  },
  {
    id: 'belsky_dunedin_2015',
    title: 'Quantification of biological aging in young adults',
    authors: 'Belsky DW, Caspi A, Houts R, et al.',
    journal: 'Proceedings of the National Academy of Sciences',
    year: 2015,
    doi: '10.1073/pnas.1506264112',
    pmid: '26150497',
    pmcid: 'PMC4522793',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4522793/',
    role: 'validation',
  },
  {
    id: 'belsky_calerie_2017',
    title: 'Change in the rate of biological aging in response to caloric restriction: CALERIE Biobank analysis',
    authors: 'Belsky DW, Huffman KM, Pieper CF, Shalev I, Kraus WE',
    journal: 'The Journals of Gerontology: Series A',
    year: 2017,
    doi: '10.1093/gerona/glx096',
    pmid: '28531269',
    pmcid: 'PMC5861848',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5861848/',
    role: 'adaptation',
  },
  {
    id: 'hastings_nhanes_iv_2019',
    title: 'Comparability of biological aging measures in the National Health and Nutrition Examination Study, 1999–2002',
    authors: 'Hastings WJ, Shalev I, Belsky DW',
    journal: 'Psychoneuroendocrinology',
    year: 2019,
    doi: '10.1016/j.psyneuen.2019.03.012',
    pmid: '30999236',
    pmcid: 'PMC6599717',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6599717/',
    role: 'validation',
  },
  {
    id: 'zhong_slas_kdm_2020',
    title: 'Estimating biological age in the Singapore Longitudinal Aging Study',
    authors: 'Zhong X, Lu Y, Gao Q, et al.',
    journal: 'The Journals of Gerontology: Series A',
    year: 2020,
    doi: '10.1093/gerona/glz146',
    pmid: '31179487',
    pmcid: null,
    url: 'https://pubmed.ncbi.nlm.nih.gov/31179487/',
    role: 'development',
  },
  {
    id: 'liu_china_kdm_2020',
    title: 'Development and validation of 2 composite aging measures using routine clinical biomarkers in the Chinese population',
    authors: 'Liu Z, Kuo PL, Zhou Y, et al.',
    journal: 'The Journals of Gerontology: Series A',
    year: 2020,
    doi: '10.1093/gerona/glaa238',
    pmid: '32946548',
    pmcid: 'PMC8521780',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8521780/',
    role: 'development',
  },
  {
    id: 'chan_ukb_kdm_2021',
    title: 'A biomarker-based biological age in UK Biobank: composition and prediction of mortality and hospital admissions',
    authors: 'Chan MS, Arnold M, Offer A, et al.',
    journal: 'The Journals of Gerontology: Series A',
    year: 2021,
    doi: '10.1093/gerona/glab069',
    pmid: '33724396',
    pmcid: 'PMC8202154',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8202154/',
    role: 'development',
  },
  {
    id: 'kwon_bioage_2021',
    title: 'A toolkit for quantification of biological age from blood chemistry and organ function test data: BioAge',
    authors: 'Kwon D, Belsky DW',
    journal: 'GeroScience',
    year: 2021,
    doi: '10.1007/s11357-021-00480-5',
    pmid: '34725754',
    pmcid: 'PMC8602613',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8602613/',
    role: 'implementation',
  },
  {
    id: 'mak_ukb_kdm_2023',
    title: 'Clinical biomarker-based biological aging and risk of cancer in the UK Biobank',
    authors: 'Mak JKL, McMurran CE, Kuja-Halkola R, et al.',
    journal: 'British Journal of Cancer',
    year: 2023,
    doi: '10.1038/s41416-023-02288-w',
    pmid: '37120669',
    pmcid: 'PMC10307789',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10307789/',
    role: 'adaptation',
  },
] as const satisfies readonly KdmEvidenceReference[];

export type KdmCalibrationEvidenceId = typeof KDM_CALIBRATION_EVIDENCE[number]['id'];

export function getKdmCalibrationEvidence(id: string): KdmEvidenceReference | undefined {
  return KDM_CALIBRATION_EVIDENCE.find(reference => reference.id === id);
}
