import type { EvidenceReference } from './models';

export const SCIENTIFIC_EVIDENCE = [
  {
    id: 'klemera_doubal_2006',
    title: 'A new approach to the concept and computation of biological age',
    authors: 'Klemera P, Doubal S',
    journal: 'Mechanisms of Ageing and Development',
    year: 2006,
    publicationType: 'model_development',
    peerReviewed: true,
    doi: '10.1016/j.mad.2005.10.004',
    pmid: '16318865',
    url: 'https://pubmed.ncbi.nlm.nih.gov/16318865/',
  },
  {
    id: 'levine_kdm_2013',
    title: 'Modeling the rate of senescence: can estimated biological age predict mortality more accurately than chronological age?',
    authors: 'Levine ME',
    journal: 'The Journals of Gerontology: Series A',
    year: 2013,
    publicationType: 'external_validation',
    peerReviewed: true,
    doi: '10.1093/gerona/gls233',
    pmid: '23213031',
    pmcid: 'PMC3660119',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23213031/',
  },
  {
    id: 'levine_phenoage_2018',
    title: 'An epigenetic biomarker of aging for lifespan and healthspan',
    authors: 'Levine ME, Lu AT, Quach A, et al.',
    journal: 'Aging',
    year: 2018,
    publicationType: 'model_development',
    peerReviewed: true,
    doi: '10.18632/aging.101414',
    pmid: '29676998',
    pmcid: 'PMC5940111',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5940111/',
  },
  {
    id: 'liu_phenoage_validation_2018',
    title: 'A new aging measure captures morbidity and mortality risk across diverse subpopulations from NHANES IV',
    authors: 'Liu Z, Kuo PL, Horvath S, et al.',
    journal: 'PLOS Medicine',
    year: 2018,
    publicationType: 'external_validation',
    peerReviewed: true,
    doi: '10.1371/journal.pmed.1002718',
    pmid: '30596641',
    pmcid: 'PMC6312200',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6312200/',
  },
  {
    id: 'lu_grimage_2019',
    title: 'DNA methylation GrimAge strongly predicts lifespan and healthspan',
    authors: 'Lu AT, Quach A, Wilson JG, et al.',
    journal: 'Aging',
    year: 2019,
    publicationType: 'model_development',
    peerReviewed: true,
    doi: '10.18632/aging.101684',
    pmid: '30669119',
    pmcid: 'PMC6366976',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6366976/',
  },
  {
    id: 'belsky_dunedinpace_2022',
    title: 'DunedinPACE, a DNA methylation biomarker of the pace of aging',
    authors: 'Belsky DW, Caspi A, Corcoran DL, et al.',
    journal: 'eLife',
    year: 2022,
    publicationType: 'model_development',
    peerReviewed: true,
    doi: '10.7554/eLife.73420',
    pmid: '35029144',
    pmcid: 'PMC8853656',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8853656/',
  },
  {
    id: 'searle_frailty_2008',
    title: 'A standard procedure for creating a frailty index',
    authors: 'Searle SD, Mitnitski A, Gahbauer EA, et al.',
    journal: 'BMC Geriatrics',
    year: 2008,
    publicationType: 'methods_standard',
    peerReviewed: true,
    doi: '10.1186/1471-2318-8-24',
    pmid: '18826625',
    pmcid: 'PMC2573877',
    url: 'https://pubmed.ncbi.nlm.nih.gov/18826625/',
  },
  {
    id: 'kaminsky_friend_2015',
    title: 'Reference standards for cardiorespiratory fitness measured with cardiopulmonary exercise testing',
    authors: 'Kaminsky LA, Arena R, Myers J',
    journal: 'Mayo Clinic Proceedings',
    year: 2015,
    publicationType: 'methods_standard',
    peerReviewed: true,
    doi: '10.1016/j.mayocp.2015.07.026',
    pmid: '26455884',
    pmcid: 'PMC4919021',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26455884/',
  },
  {
    id: 'mandsager_crf_2018',
    title: 'Association of cardiorespiratory fitness with long-term mortality among adults undergoing exercise treadmill testing',
    authors: 'Mandsager K, Harb S, Cremer P, et al.',
    journal: 'JAMA Network Open',
    year: 2018,
    publicationType: 'prospective_cohort',
    peerReviewed: true,
    doi: '10.1001/jamanetworkopen.2018.3605',
    pmid: '30646252',
    pmcid: 'PMC6324439',
    url: 'https://pubmed.ncbi.nlm.nih.gov/30646252/',
  },
  {
    id: 'nunan_hrv_2010',
    title: 'A quantitative systematic review of normal values for short-term heart rate variability in healthy adults',
    authors: 'Nunan D, Sandercock GRH, Brodie DA',
    journal: 'Pacing and Clinical Electrophysiology',
    year: 2010,
    publicationType: 'systematic_review_meta_analysis',
    peerReviewed: true,
    doi: '10.1111/j.1540-8159.2010.02841.x',
    pmid: '20663071',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20663071/',
  },
  {
    id: 'garavaglia_hrv_2021',
    title: 'The effect of age on the heart rate variability of healthy subjects',
    authors: 'Garavaglia L, Gulich D, Defeo MM, et al.',
    journal: 'PLOS ONE',
    year: 2021,
    publicationType: 'prospective_cohort',
    peerReviewed: true,
    doi: '10.1371/journal.pone.0255894',
    pmid: '34624048',
    pmcid: 'PMC8500436',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34624048/',
  },
  {
    id: 'zhang_resting_hr_2016',
    title: 'Resting heart rate and all-cause and cardiovascular mortality in the general population: a meta-analysis',
    authors: 'Zhang D, Shen X, Qi X',
    journal: 'CMAJ',
    year: 2016,
    publicationType: 'systematic_review_meta_analysis',
    peerReviewed: true,
    doi: '10.1503/cmaj.150535',
    pmid: '26598376',
    pmcid: 'PMC4754196',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26598376/',
  },
  {
    id: 'cappuccio_sleep_2010',
    title: 'Sleep duration and all-cause mortality: a systematic review and meta-analysis of prospective studies',
    authors: "Cappuccio FP, D'Elia L, Strazzullo P, Miller MA",
    journal: 'Sleep',
    year: 2010,
    publicationType: 'systematic_review_meta_analysis',
    peerReviewed: true,
    doi: '10.1093/sleep/33.5.585',
    pmid: '20469800',
    pmcid: 'PMC2864873',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20469800/',
  },
  {
    id: 'windred_sleep_regularity_2024',
    title: 'Sleep regularity is a stronger predictor of mortality risk than sleep duration: a prospective cohort study',
    authors: 'Windred DP, Jones SE, Russell A, et al.',
    journal: 'Sleep',
    year: 2024,
    publicationType: 'prospective_cohort',
    peerReviewed: true,
    doi: '10.1093/sleep/zsad253',
    pmid: '37738616',
    pmcid: 'PMC10782501',
    url: 'https://pubmed.ncbi.nlm.nih.gov/37738616/',
  },
  {
    id: 'english_nutrition_2021',
    title: 'Evaluation of dietary patterns and all-cause mortality: a systematic review',
    authors: 'English LK, Ard JD, Bailey RL, et al.',
    journal: 'JAMA Network Open',
    year: 2021,
    publicationType: 'systematic_review_meta_analysis',
    peerReviewed: true,
    doi: '10.1001/jamanetworkopen.2021.22277',
    pmid: '34463743',
    pmcid: 'PMC8408672',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34463743/',
  },
  {
    id: 'varadhan_inflammation_2014',
    title: 'Simple biologically informed inflammatory index of two serum cytokines predicts 10 year all-cause mortality in older adults',
    authors: 'Varadhan R, Yao W, Matteini A, et al.',
    journal: 'The Journals of Gerontology: Series A',
    year: 2014,
    publicationType: 'prospective_cohort',
    peerReviewed: true,
    doi: '10.1093/gerona/glt023',
    pmid: '23689826',
    pmcid: 'PMC4038244',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23689826/',
  },
  {
    id: 'li_cardiometage_2026',
    title: 'CardioMetAge estimates cardiometabolic aging and predicts disease outcomes',
    authors: 'Li Y, Xu X, Zheng Y, et al.',
    journal: 'BMC Medicine',
    year: 2026,
    publicationType: 'model_development',
    peerReviewed: true,
    doi: '10.1186/s12916-026-04621-5',
    pmid: '41620721',
    pmcid: 'PMC12947333',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12947333/',
  },
] as const satisfies readonly EvidenceReference[];
