import type { ScientificModelVersion } from './eligibilityModels';

export const SCIENTIFIC_MODEL_VERSIONS = [
  {
    modelId: 'clinical_phenoage',
    version: 'clinical-phenoage/1.0.0',
    lifecycle: 'active',
    inputPolicyId: 'clinical_phenoage_complete_visit',
    minimumAgeYears: 20,
    maximumAgeYears: null,
    allowedSex: null,
    requiresLaboratoryContext: true,
    requiredCalibrationIds: [],
    requiresDevice: false,
    supportedDeviceTypes: [],
    minimumHistoryObservations: 1,
    minimumHistoryDays: 0,
    sparseHistoryIsWarning: true,
    deprecatedInputIds: [],
    evidenceReferenceIds: ['levine_phenoage_2018', 'liu_phenoage_validation_2018'],
    scientificNotes: [
      'Eligibility applies only to the published clinical model and exact published input units.',
      'A single complete visit is cross-sectional evidence and does not establish pace of aging.',
    ],
  },
  {
    modelId: 'kdm_biological_age', version: 'kdm/unconfigured-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: 'validated_kdm_calibration', minimumAgeYears: null, maximumAgeYears: null,
    allowedSex: null, requiresLaboratoryContext: true, requiredCalibrationIds: [],
    requiresDevice: false, supportedDeviceTypes: [], minimumHistoryObservations: 1,
    minimumHistoryDays: 0, sparseHistoryIsWarning: false, deprecatedInputIds: [],
    evidenceReferenceIds: ['klemera_doubal_2006', 'levine_kdm_2013'],
    scientificNotes: ['KDM cannot execute until a separately validated calibration version is registered.'],
  },
  {
    modelId: 'levine_2013_kdm', version: 'levine-kdm-nhanes-iii/1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: 30, maximumAgeYears: 75, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: ['nhanes-iii-levine-2013'],
    requiresDevice: false, supportedDeviceTypes: [], minimumHistoryObservations: 1,
    minimumHistoryDays: 0, sparseHistoryIsWarning: false, deprecatedInputIds: [],
    evidenceReferenceIds: ['levine_kdm_2013'], scientificNotes: ['Historical research implementation only.'],
  },
  {
    modelId: 'dnam_phenoage', version: 'dnam-phenoage/1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 1, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['levine_phenoage_2018'],
    scientificNotes: ['Research-only pending assay and preprocessing validation.'],
  },
  {
    modelId: 'dunedinpace', version: 'dunedinpace/1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 1, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['belsky_dunedinpace_2022'],
    scientificNotes: ['Pace-of-aging research output is not an age-in-years model.'],
  },
  {
    modelId: 'grim_age', version: 'grimage/1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 1, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['lu_grimage_2019'],
    scientificNotes: ['Mortality-trained methylation surrogate remains research-only.'],
  },
  {
    modelId: 'frailty_index', version: 'frailty-index/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['searle_frailty_2008'],
    scientificNotes: ['Frailty is context and is not eligible for biological-age calculation.'],
  },
  {
    modelId: 'vo2max_normative_ageing', version: 'friend-vo2max/context-1.0.0', lifecycle: 'research_only',
    inputPolicyId: 'quality_controlled_vo2max', minimumAgeYears: 20, maximumAgeYears: 79,
    allowedSex: null, requiresLaboratoryContext: false, requiredCalibrationIds: ['friend-2015'],
    requiresDevice: true, supportedDeviceTypes: ['clinical-cpet'], minimumHistoryObservations: 1,
    minimumHistoryDays: 0, sparseHistoryIsWarning: true, deprecatedInputIds: [],
    evidenceReferenceIds: ['kaminsky_friend_2015', 'mandsager_crf_2018'],
    scientificNotes: ['Accepted for modifier research, not biological-age calculation.'],
  },
  {
    modelId: 'hrv_derived_age', version: 'hrv-derived-age/unsupported-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: true,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['nunan_hrv_2010', 'garavaglia_hrv_2021'],
    scientificNotes: ['No validated generic HRV-to-age transformation exists.'],
  },
  {
    modelId: 'resting_heart_rate_literature', version: 'resting-heart-rate/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['zhang_resting_hr_2016'],
    scientificNotes: ['Association evidence is context only.'],
  },
  {
    modelId: 'sleep_duration_literature', version: 'sleep-duration/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['cappuccio_sleep_2010'],
    scientificNotes: ['Sleep-duration association is not an age model.'],
  },
  {
    modelId: 'sleep_consistency_literature', version: 'sleep-regularity/research-1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: true,
    supportedDeviceTypes: ['research-actigraphy'], minimumHistoryObservations: 7, minimumHistoryDays: 7,
    sparseHistoryIsWarning: true, deprecatedInputIds: [], evidenceReferenceIds: ['windred_sleep_regularity_2024'],
    scientificNotes: ['Emerging observational evidence only; no biological-age transformation.'],
  },
  {
    modelId: 'cardiorespiratory_fitness_literature', version: 'crf-literature/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['kaminsky_friend_2015', 'mandsager_crf_2018'],
    scientificNotes: ['Outcome literature does not itself define an executable age model.'],
  },
  {
    modelId: 'nutrition_longevity_literature', version: 'nutrition-longevity/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['english_nutrition_2021'],
    scientificNotes: ['Dietary outcome evidence is context only.'],
  },
  {
    modelId: 'inflammation_literature', version: 'inflammation/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['varadhan_inflammation_2014', 'levine_phenoage_2018'],
    scientificNotes: ['Independent use would risk double counting clinical PhenoAge inputs.'],
  },
  {
    modelId: 'cardiometabolic_risk_literature', version: 'cardiometabolic-risk/context-1.0.0', lifecycle: 'unsupported',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: false, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 0, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['li_cardiometage_2026', 'levine_phenoage_2018'],
    scientificNotes: ['Disease-risk context is not biological age.'],
  },
  {
    modelId: 'cardiometage', version: 'cardiometage/research-1.0.0', lifecycle: 'research_only',
    inputPolicyId: null, minimumAgeYears: null, maximumAgeYears: null, allowedSex: null,
    requiresLaboratoryContext: true, requiredCalibrationIds: [], requiresDevice: false,
    supportedDeviceTypes: [], minimumHistoryObservations: 1, minimumHistoryDays: 0,
    sparseHistoryIsWarning: false, deprecatedInputIds: [], evidenceReferenceIds: ['li_cardiometage_2026'],
    scientificNotes: ['Deferred pending independent replication and implementation audit.'],
  },
] as const satisfies readonly ScientificModelVersion[];
