import type { ScientificModelAlias, ScientificModelRecord } from './models';

export const SCIENTIFIC_MODEL_REGISTRY = [
  {
    id: 'clinical_phenoage',
    modelName: 'Levine Clinical Phenotypic Age (PhenoAge)',
    category: 'clinical_biomarker_composite',
    classification: 'core_biological_age_model',
    useDecision: 'accepted_candidate',
    purpose: 'Represent mortality-calibrated physiological status in age-equivalent years from a fixed clinical blood panel.',
    primaryInputs: ['Chronological age', 'Albumin', 'Creatinine', 'Glucose', 'C-reactive protein', 'Lymphocyte percentage', 'Mean cell volume', 'Red cell distribution width', 'Alkaline phosphatase', 'White blood cell count'],
    outputType: 'biological_age_years',
    validationStatus: 'externally_validated',
    population: ['NHANES III United States adults for derivation', 'NHANES IV United States adults for validation', 'Additional cohort replications'],
    clinicalAdoption: 'limited_specialty',
    strengths: ['Published fixed clinical input set', 'External mortality and morbidity validation', 'Commonly available clinical measurements', 'Human-readable inputs'],
    knownLimitations: ['Mortality-calibrated construct is not a direct measurement of aging mechanisms', 'Chronological age is an input', 'Sensitive to assay, unit, acute illness, and collection-window differences', 'Cross-sectional output does not establish pace of aging'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Compatible laboratory assays', 'Exact published unit normalization', 'Chronological age at collection'],
    evidenceReferenceIds: ['levine_phenoage_2018', 'liu_phenoage_validation_2018'],
    inputPolicyId: 'clinical_phenoage_complete_visit',
    relatedModelIds: ['dnam_phenoage'],
    notes: ['Phenotypic Age and clinical PhenoAge refer to this same canonical model in this registry.', 'DNAm PhenoAge is a separate epigenetic model and must not be treated as interchangeable.'],
  },
  {
    id: 'kdm_biological_age',
    modelName: 'Klemera–Doubal Method (KDM)',
    category: 'clinical_biomarker_composite',
    classification: 'core_biological_age_model',
    useDecision: 'accepted_candidate',
    purpose: 'Estimate an age-equivalent latent biological-age construct from age-associated biomarkers and a reference-population calibration.',
    primaryInputs: ['Chronological age', 'Calibration-specific biomarker panel', 'Versioned reference-population parameters'],
    outputType: 'biological_age_years',
    validationStatus: 'replicated_associations',
    population: ['Method defined through simulation', 'Multiple cohort-specific implementations', 'Population depends on selected calibration'],
    clinicalAdoption: 'research_only',
    strengths: ['Explicit statistical framework', 'Supports model precision estimation', 'Outperformed comparison algorithms in the Levine 2013 NHANES III analysis'],
    knownLimitations: ['KDM is a method rather than one universal fixed model', 'Results depend on biomarker selection and reference calibration', 'Chronological age can be incorporated as a biomarker', 'Different implementations are not automatically comparable'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Versioned population calibration', 'Exact calibration biomarker panel', 'Measurement protocol compatibility'],
    evidenceReferenceIds: ['klemera_doubal_2006', 'levine_kdm_2013'],
    inputPolicyId: 'validated_kdm_calibration',
    relatedModelIds: ['levine_2013_kdm'],
    notes: ['Acceptance applies only to a separately reviewed, versioned calibration.', 'Changing biomarkers or calibration population creates a new implementation requiring validation.'],
  },
  {
    id: 'levine_2013_kdm',
    modelName: 'Levine 2013 NHANES III KDM Biological Age',
    category: 'clinical_biomarker_composite',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Historical NHANES III implementation used to compare KDM with four other biological-age algorithms.',
    primaryInputs: ['Chronological age', 'NHANES III KDM biomarker battery', 'Published sex-specific calibration parameters'],
    outputType: 'biological_age_years',
    validationStatus: 'replicated_associations',
    population: ['9,389 NHANES III participants aged 30–75 years', 'United States population sample'],
    clinicalAdoption: 'research_only',
    strengths: ['Long mortality follow-up', 'Direct comparison of multiple biological-age algorithms', 'Historically important clinical KDM implementation'],
    knownLimitations: ['Historical NHANES assay and population calibration', 'Input availability differs across modern datasets', 'Not interchangeable with arbitrary KDM panels', 'No implementation is authorized by this registry'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Exact historical biomarker definitions', 'Published NHANES III calibration parameters'],
    evidenceReferenceIds: ['levine_kdm_2013'],
    inputPolicyId: null,
    relatedModelIds: ['kdm_biological_age'],
    notes: ['This resolves the requested “Biological Age (Levine original)” candidate.', 'It is retained for audit history and must not be counted in addition to a KDM implementation.'],
  },
  {
    id: 'dnam_phenoage',
    modelName: 'DNAm PhenoAge',
    category: 'epigenetic',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Estimate the clinical Phenotypic Age target from whole-blood DNA methylation.',
    primaryInputs: ['Genome-wide DNA methylation', '513 CpG features', 'Validated preprocessing and cell-composition handling'],
    outputType: 'biological_age_years',
    validationStatus: 'externally_validated',
    population: ['InCHIANTI derivation', 'Multiple blood cohorts', 'Multiple tissues evaluated for association'],
    clinicalAdoption: 'research_only',
    strengths: ['Peer-reviewed model specification', 'Validated against multiple aging-related outcomes', 'Biological pathway analyses published'],
    knownLimitations: ['Requires specialized methylation assay and preprocessing', 'Batch and cell-composition effects', 'Clinical utility is not established', 'The epigenetic output is distinct from clinical PhenoAge'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Illumina-compatible methylation data', 'Validated preprocessing pipeline', 'Versioned CpG coefficients'],
    evidenceReferenceIds: ['levine_phenoage_2018'],
    inputPolicyId: null,
    relatedModelIds: ['clinical_phenoage'],
    notes: ['Deferred until assay provenance, reproducibility, licensing, and population validation are reviewed for production use.'],
  },
  {
    id: 'dunedinpace',
    modelName: 'DunedinPACE',
    category: 'epigenetic',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Estimate pace of aging from a single whole-blood DNA-methylation assay trained against longitudinal organ-system change.',
    primaryInputs: ['Genome-wide blood DNA methylation', '173 CpG features', 'Validated normalization and quality control'],
    outputType: 'pace_of_aging',
    validationStatus: 'externally_validated',
    population: ['Dunedin 1972–1973 birth cohort for development', 'Five additional datasets reported in the primary paper'],
    clinicalAdoption: 'research_only',
    strengths: ['Target derived from two decades of longitudinal multi-system data', 'High reported test-retest reliability', 'External associations with morbidity, disability, and mortality'],
    knownLimitations: ['Output is pace, not biological age in years', 'Single-year New Zealand birth cohort anchors the training target', 'Specialized assay and preprocessing required', 'Not a clinical diagnostic or treatment-response measure'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Illumina methylation array', 'Official algorithm implementation', 'Reference normalization probes'],
    evidenceReferenceIds: ['belsky_dunedinpace_2022'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['It cannot be merged with age-in-years outputs without a separately validated scientific model.'],
  },
  {
    id: 'grim_age',
    modelName: 'DNAm GrimAge',
    category: 'epigenetic',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Provide a DNA-methylation surrogate age trained from smoking and plasma-protein surrogates associated with mortality.',
    primaryInputs: ['Whole-blood DNA methylation', 'DNA methylation surrogates for smoking and plasma proteins', 'Chronological age and sex variables used by the published model'],
    outputType: 'mortality_risk_surrogate_age',
    validationStatus: 'externally_validated',
    population: ['Framingham Heart Study derivation and test pedigrees', 'Multiple validation cohorts'],
    clinicalAdoption: 'research_only',
    strengths: ['Strong mortality and healthspan associations', 'Independent test partition and multiple validation datasets', 'Published component structure'],
    knownLimitations: ['Mortality-trained surrogate is not a direct measurement of aging', 'Smoking signal is embedded in the construct', 'Specialized methylation assay and preprocessing required', 'Clinical utility is not established'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Whole-blood methylation array', 'Versioned algorithm and preprocessing', 'Compatible blood specimen'],
    evidenceReferenceIds: ['lu_grimage_2019'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['Retained for research comparison only; mortality prediction must never be presented as lifespan estimation.'],
  },
  {
    id: 'frailty_index',
    modelName: 'Deficit-Accumulation Frailty Index',
    category: 'frailty',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Describe accumulated health deficits and vulnerability, particularly in older populations.',
    primaryInputs: ['Sufficient predefined health deficits', 'Deficit coding rules', 'Population-appropriate assessment'],
    outputType: 'frailty_proportion',
    validationStatus: 'replicated_associations',
    population: ['Predominantly older adults', 'Multiple population and clinical cohorts'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Reproducible construction procedure', 'Strong association with adverse outcomes', 'Broad geriatric interpretability'],
    knownLimitations: ['Measures deficit accumulation rather than age in years', 'Item composition varies by dataset', 'Less informative in younger low-deficit populations', 'Can include disease and disability consequences'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_body_of_evidence',
    externalDependencies: ['Validated deficit set', 'Consistent deficit coding', 'Adequate item completeness'],
    evidenceReferenceIds: ['searle_frailty_2008'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['May support future clinical context but must not alter biological age without independent validation.'],
  },
  {
    id: 'vo2max_normative_ageing',
    modelName: 'VO2max Normative Ageing References',
    category: 'cardiorespiratory_fitness',
    classification: 'candidate_modifier',
    useDecision: 'accepted_candidate',
    purpose: 'Place directly measured cardiorespiratory fitness in age- and population-specific normative context.',
    primaryInputs: ['Directly measured VO2max', 'Chronological age', 'Reference stratification variables', 'CPET protocol and quality criteria'],
    outputType: 'normative_fitness_context',
    validationStatus: 'replicated_associations',
    population: ['FRIEND United States adults aged 20–79 without cardiovascular disease', 'Other reference populations require separate review'],
    clinicalAdoption: 'limited_specialty',
    strengths: ['Direct CPET measurement', 'Large multicenter reference dataset', 'Strong cardiorespiratory-fitness outcome literature'],
    knownLimitations: ['Normative percentile is not biological age', 'Reference values depend on population, sex, modality, and protocol', 'Wearable estimates are not interchangeable with maximal CPET', 'No validated biological-age weighting exists'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_body_of_evidence',
    externalDependencies: ['Quality-controlled maximal CPET', 'Versioned normative reference tables'],
    evidenceReferenceIds: ['kaminsky_friend_2015', 'mandsager_crf_2018'],
    inputPolicyId: 'quality_controlled_vo2max',
    relatedModelIds: ['cardiorespiratory_fitness_literature'],
    notes: ['Accepted only for future modifier evaluation; it currently has no permission to change an age output.'],
  },
  {
    id: 'hrv_derived_age',
    modelName: 'Generic HRV-Derived Biological Age',
    category: 'autonomic',
    classification: 'rejected',
    useDecision: 'excluded',
    purpose: 'Proposed conversion of heart-rate variability into biological age.',
    primaryInputs: ['Heart-rate variability measures', 'Recording and artifact-processing protocol'],
    outputType: 'physiologic_association',
    validationStatus: 'not_validated_as_age_model',
    population: ['Heterogeneous healthy and clinical cohorts with method-dependent results'],
    clinicalAdoption: 'none',
    strengths: ['Age associations are reported', 'Noninvasive repeated measurement is feasible'],
    knownLimitations: ['No canonical validated age transformation', 'Very large interindividual variability', 'Strong dependence on recording duration, posture, breathing, artifacts, device, medication, and fitness', 'Normative literature identifies methodological inconsistency'],
    evidenceLevel: 'insufficient',
    peerReviewStatus: 'peer_reviewed_association_only',
    externalDependencies: ['Standardized ECG-quality signal', 'Protocol-specific reference data'],
    evidenceReferenceIds: ['nunan_hrv_2010', 'garavaglia_hrv_2021'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['HRV may remain a Recovery observation; it must not influence biological age under current evidence.'],
  },
  {
    id: 'resting_heart_rate_literature',
    modelName: 'Resting Heart-Rate Ageing Literature',
    category: 'autonomic',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Document population associations between resting heart rate and mortality outcomes.',
    primaryInputs: ['Resting heart rate', 'Measurement context', 'Medication and rhythm context'],
    outputType: 'physiologic_association',
    validationStatus: 'not_validated_as_age_model',
    population: ['General-population prospective cohorts', 'Substantial study heterogeneity'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Simple established physiological measure', 'Large prospective evidence base'],
    knownLimitations: ['Association does not define biological age', 'Confounded by fitness, medication, illness, autonomic state, and rhythm', 'Meta-analysis reported substantial heterogeneity and publication bias'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_association_only',
    externalDependencies: ['Standardized resting measurement', 'Medication and rhythm provenance'],
    evidenceReferenceIds: ['zhang_resting_hr_2016'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['Monitoring context only; no age transformation or modifier is supported.'],
  },
  {
    id: 'sleep_duration_literature',
    modelName: 'Sleep Duration and Longevity Literature',
    category: 'sleep',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Document associations between habitual sleep duration and mortality.',
    primaryInputs: ['Habitual sleep duration', 'Measurement method', 'Observation window'],
    outputType: 'exposure_outcome_association',
    validationStatus: 'not_validated_as_age_model',
    population: ['Prospective adult cohorts', 'Predominantly questionnaire-based evidence in the foundational meta-analysis'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Large prospective evidence base', 'Repeated observation is feasible'],
    knownLimitations: ['U-shaped observational associations do not define an age transformation', 'Reverse causation and residual confounding', 'Self-report and device estimates are not interchangeable', 'Sleep need varies by person and context'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_association_only',
    externalDependencies: ['Source-attributed sleep measurement', 'Sufficient observation window'],
    evidenceReferenceIds: ['cappuccio_sleep_2010'],
    inputPolicyId: null,
    relatedModelIds: ['sleep_consistency_literature'],
    notes: ['Relevant to Sleep domain interpretation, not biological-age estimation.'],
  },
  {
    id: 'sleep_consistency_literature',
    modelName: 'Sleep Regularity and Consistency Literature',
    category: 'sleep',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Assess whether objective sleep-wake regularity provides reproducible aging-relevant longitudinal context.',
    primaryInputs: ['Device-derived sleep-wake states', 'Consecutive observation window', 'Validated regularity algorithm'],
    outputType: 'exposure_outcome_association',
    validationStatus: 'replicated_associations',
    population: ['UK Biobank middle-aged and older adults', 'Seven-day accelerometry windows'],
    clinicalAdoption: 'research_only',
    strengths: ['Objective large-cohort evidence', 'Longitudinal mortality follow-up', 'Captures behavior distinct from duration'],
    knownLimitations: ['No validated biological-age transformation', 'Short measurement window relative to follow-up', 'Observational evidence and residual confounding', 'Generalizability beyond older UK Biobank participants requires validation'],
    evidenceLevel: 'limited',
    peerReviewStatus: 'peer_reviewed_association_only',
    externalDependencies: ['Validated sleep-state inference', 'Continuous compatible accelerometry'],
    evidenceReferenceIds: ['windred_sleep_regularity_2024'],
    inputPolicyId: null,
    relatedModelIds: ['sleep_duration_literature'],
    notes: ['Promising monitoring evidence, but insufficient for age influence.'],
  },
  {
    id: 'cardiorespiratory_fitness_literature',
    modelName: 'Cardiorespiratory Fitness and Longevity Literature',
    category: 'cardiorespiratory_fitness',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Document the outcome evidence supporting cardiorespiratory fitness as an important health context.',
    primaryInputs: ['Direct or protocol-specific exercise capacity', 'Age and population context'],
    outputType: 'exposure_outcome_association',
    validationStatus: 'replicated_associations',
    population: ['Healthy and clinically referred adults', 'Multiple age and sex strata'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Strong and consistent outcome association', 'Objective testing methods available', 'Clinically interpretable'],
    knownLimitations: ['Mortality association is not an age model', 'Estimated METs and measured VO2max are different evidence types', 'Referral cohorts can introduce selection bias'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_body_of_evidence',
    externalDependencies: ['Protocol and modality provenance'],
    evidenceReferenceIds: ['kaminsky_friend_2015', 'mandsager_crf_2018'],
    inputPolicyId: null,
    relatedModelIds: ['vo2max_normative_ageing'],
    notes: ['The evidence supports fitness monitoring; only the separately registered VO2max candidate may undergo future modifier evaluation.'],
  },
  {
    id: 'nutrition_longevity_literature',
    modelName: 'Nutrition-Related Longevity Literature',
    category: 'nutrition',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Document associations between dietary patterns and longevity outcomes.',
    primaryInputs: ['Validated dietary assessment', 'Dietary pattern definition', 'Longitudinal outcome follow-up'],
    outputType: 'exposure_outcome_association',
    validationStatus: 'not_validated_as_age_model',
    population: ['Adult and older-adult cohorts across multiple high-development countries'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Large systematic evidence base', 'Consistency across several nutrient-dense dietary patterns'],
    knownLimitations: ['Mostly observational evidence', 'Measurement error and cultural variation in dietary assessment', 'No single validated nutrition-to-biological-age model', 'Diet labels and component definitions vary'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_body_of_evidence',
    externalDependencies: ['Validated dietary instrument', 'Population-appropriate pattern definition'],
    evidenceReferenceIds: ['english_nutrition_2021'],
    inputPolicyId: null,
    relatedModelIds: [],
    notes: ['Nutrition may inform its own domain but must not influence biological age under current evidence.'],
  },
  {
    id: 'inflammation_literature',
    modelName: 'Inflammation and Ageing Literature',
    category: 'inflammation',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Document associations between inflammatory markers, aging-related outcomes, and mortality.',
    primaryInputs: ['Source-attributed inflammatory biomarkers', 'Clinical and collection context'],
    outputType: 'physiologic_association',
    validationStatus: 'replicated_associations',
    population: ['Predominantly older adult cohorts', 'Population-specific marker panels'],
    clinicalAdoption: 'limited_specialty',
    strengths: ['Biologically plausible aging relevance', 'Prospective outcome associations', 'Some markers are routinely measured'],
    knownLimitations: ['Inflammation is nonspecific and affected by acute illness', 'Marker panels and assays vary', 'CRP and WBC already contribute to clinical PhenoAge, creating double-counting risk', 'No independent modifier transformation is validated'],
    evidenceLevel: 'moderate',
    peerReviewStatus: 'peer_reviewed_association_only',
    externalDependencies: ['Assay-specific provenance', 'Acute-illness context', 'Repeat confirmation where appropriate'],
    evidenceReferenceIds: ['varadhan_inflammation_2014', 'levine_phenoage_2018'],
    inputPolicyId: null,
    relatedModelIds: ['clinical_phenoage'],
    notes: ['Context only. It must not duplicate biomarkers already represented inside a core model.'],
  },
  {
    id: 'cardiometabolic_risk_literature',
    modelName: 'Cardiometabolic Risk Literature',
    category: 'cardiometabolic',
    classification: 'context_only',
    useDecision: 'reference_only',
    purpose: 'Distinguish validated cardiometabolic risk assessment from biological-age estimation.',
    primaryInputs: ['Model-specific cardiometabolic factors', 'Population and outcome horizon', 'Clinical measurement provenance'],
    outputType: 'exposure_outcome_association',
    validationStatus: 'not_validated_as_age_model',
    population: ['Varies by risk model and clinical outcome'],
    clinicalAdoption: 'established_context_measure',
    strengths: ['Clinically important and often well-validated for defined disease outcomes', 'Uses interpretable clinical factors'],
    knownLimitations: ['Disease risk is not biological age', 'Outcome horizons and populations vary', 'Overlap with clinical biomarker age models creates double-counting risk', 'A risk estimate cannot be converted to age without validated calibration'],
    evidenceLevel: 'strong',
    peerReviewStatus: 'peer_reviewed_body_of_evidence',
    externalDependencies: ['A named validated risk model', 'Outcome-specific calibration'],
    evidenceReferenceIds: ['li_cardiometage_2026', 'levine_phenoage_2018'],
    inputPolicyId: null,
    relatedModelIds: ['cardiometage', 'clinical_phenoage'],
    notes: ['Risk tools may remain clinically useful outside the future biological-age engine.'],
  },
  {
    id: 'cardiometage',
    modelName: 'CardioMetAge',
    category: 'cardiometabolic',
    classification: 'research_only',
    useDecision: 'deferred',
    purpose: 'Estimate an age-equivalent cardiometabolic construct calibrated to cardiometabolic disease mortality.',
    primaryInputs: ['Chronological age', 'Twelve published clinical biomarkers', 'Reference-population calibration'],
    outputType: 'mortality_risk_surrogate_age',
    validationStatus: 'externally_validated',
    population: ['NHANES III derivation', 'Continuous NHANES testing', 'UK Biobank validation'],
    clinicalAdoption: 'research_only',
    strengths: ['External cohort testing', 'Common clinical input concept', 'Direct cardiometabolic outcome focus'],
    knownLimitations: ['Single recent model publication', 'Mortality-risk-equivalent age is not a direct measurement of aging', 'Independent replication and subgroup validation remain limited', 'Exact production implementation and calibration availability require audit'],
    evidenceLevel: 'limited',
    peerReviewStatus: 'peer_reviewed_primary_model',
    externalDependencies: ['Authoritative coefficients', 'Versioned NHANES calibration', 'Independent implementation verification'],
    evidenceReferenceIds: ['li_cardiometage_2026'],
    inputPolicyId: null,
    relatedModelIds: ['cardiometabolic_risk_literature'],
    notes: ['Added because it was peer reviewed before this audit was completed.', 'Deferred pending independent replication, implementation audit, and overlap analysis.'],
  },
] as const satisfies readonly ScientificModelRecord[];

export const SCIENTIFIC_MODEL_ALIASES = [
  {
    alias: 'Levine PhenoAge',
    canonicalModelId: 'clinical_phenoage',
    clarification: 'Vitalspan uses this label for the non-epigenetic clinical Phenotypic Age model unless DNAm PhenoAge is named explicitly.',
  },
  {
    alias: 'Phenotypic Age',
    canonicalModelId: 'clinical_phenoage',
    clarification: 'This is an alias, not a second model; duplicate registration would create double counting.',
  },
  {
    alias: 'Biological Age (Levine original)',
    canonicalModelId: 'levine_2013_kdm',
    clarification: 'This refers to Levine’s 2013 NHANES III implementation of KDM, not the later clinical PhenoAge model.',
  },
] as const satisfies readonly ScientificModelAlias[];
